console tty0 for kvm container
lf-edge/eve pull request #1286
Opened 2020-08-10 13:57 UTC by giggsoff

Move from hvc0 to tty0 lets me see the output on the VNC console for "containers" running on top of KVM HV.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

2020-08-14 00:18 UTC, rvs commented
Actually, maybe a better question for @giggsoff is this: do we need the same for Xen? Currently Xen also only uses hvc0 and if that works -- it could provide some clues as to why VM is picking it up.

2020-11-13 19:18 UTC, eriknordmark requested changes
+1 to Roman's comment.

2020-11-17 20:01 UTC, rvs commented
Hey @giggsoff -- any chance you can dig into it this week to provide some clues?

2020-11-18 07:19 UTC, giggsoff commented
I will try again, but in my previous attempt, I cannot bring logs and VNC to work at the same time

2020-11-18 07:22 UTC, rvs commented
Welp, just provide exact steps to repro -- and we can go from there @giggsoff

2020-11-18 15:27 UTC, giggsoff commented
Hi, @rvs. In the latest commit, I add `console=tty0` only in the variant of `EnableVnc`. With `console=tty0` we cannot see logs of our initrd and entrypoint inside serial output (only kernel log), but can interact with VNC console.

2020-11-18 18:33 UTC, rvs approved these changes
LGTM -- this makes sense now @giggsoff -- 10x!

2020-11-19 01:40 UTC, merged