fix fatal inside verifier
lf-edge/eve pull request #1472
Opened 2020-09-22 08:59 UTC by giggsoff

I see in syslog:
```
2020-09-22T07:38:29.025975+00:00 linuxkit-525400123456 pillar.out {"file":"/pillar/agentlog/agentlog.go:208","func":"github.com/lf-edge/eve/pkg/pillar/agentlog.printStack","level":"error","msg":"goroutine 890 [running]:\ngithub.com/lf-edge/eve/pkg/pillar/agentlog.getStacks(0xc000c1eb00, 0x0, 0x0)\n\t/pillar/agentlog/agentlog.go:408 +0x78\ngithub.com/lf-edge/eve/pkg/pillar/agentlog.printStack(0xc000390120, 0x7ffeacddcf5b, 0x6, 0x4b9)\n\t/pillar/agentlog/agentlog.go:204 +0x38\ngithub.com/lf-edge/eve/pkg/pillar/agentlog.Init.func1()\n\t/pillar/agentlog/agentlog.go:566 +0x45\ngithub.com/sirupsen/logrus.runHandler(0xc0002e20c0)\n\t/pillar/vendor/github.com/sirupsen/logrus/alt_exit.go:39 +0x43\ngithub.com/sirupsen/logrus.runHandlers()\n\t/pillar/vendor/github.com/sirupsen/logrus/alt_exit.go:44 +0x4b\ngithub.com/sirupsen/logrus.(*Logger).Exit(0xc000078c60, 0x1)\n\t/pillar/vendor/github.com/sirupsen/logrus/logger.go:285 +0x22\ngithub.com/sirupsen/logrus.(*Entry).Fatalf(0xc001392fc0, 0x1a0802c, 0x67, 0xc000163ae0, 0x2, 0x2)\n\t/pillar/vendor/github.com/sirupsen/logrus/entry.go:369 +0x7f\ngithub.com/lf-edge/eve/pkg/pillar/base.(*LogObject).Fatalf(0xc0002510a0, 0x1a0802c, 0x67, 0xc000163ae0, 0x2, 0x2)\n\t/pillar/base/log.go:136 +0x81\ngithub.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.MaybeRemoveVerifyImageConfig(0xc0000b5a00, 0xc000319740, 0x40)\n\t/pillar/cmd/volumemgr/handleverifier.go:88 +0x3a9\ngithub.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.doUpdateContentTree(0xc0000b5a00, 0xc000165680, 0x40)\n\t/pillar/cmd/volumemgr/updatestatus.go:289 +0x10dc\ngithub.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.updateStatusByBlob(0xc0000b5a00, 0xc000b8c740, 0x40)\n\t/pillar/cmd/volumemgr/updatestatus.go:482 +0x1fe\ngithub.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.handleVerifyImageStatusModify(0x1773a40, 0xc0000b5a00, 0xc000b8c680, 0x40, 0x193abc0, 0xc000bfa800)\n\t/pillar/cmd/volumemgr/handleverifier.go:202 +0x342\ngithub.com/lf-edge/eve/pkg/pillar/pubsub.handleModify(0x18df780, 0xc0005c1000, 0xc000b8c680, 0x40, 0xc000acc700, 0x1b6, 0x1b6)\n\t/pillar/pubsub/subscribe.go:245 +0x687\ngithub.com/lf-edge/eve/pkg/pillar/pubsub.(*SubscriptionImpl).ProcessChange(0xc0005c1000, 0x3, 0xc000b8c680, 0x40, 0xc000acc700, 0x1b6, 0x1b6)\n\t/pillar/pubsub/subscribe.go:121 +0x322\ngithub.com/lf-edge/eve/pkg/pillar/cmd/volumemgr.Run(0xc000a66ff0, 0xc000078c60, 0xc0002510a0, 0x0)\n\t/pillar/cmd/volumemgr/volumemgr.go:519 +0x408f\nmain.startAgentAndDone(0x1a18dd0, 0xc000078e00, 0xc0009584d0, 0x9, 0xc000a66ff0, 0xc000078c60, 0xc0002510a0)\n\t/pillar/zedbox/zedbox.go:230 +0x62\ncreated by main.handleService\n\t/pillar/zedbox/zedbox.go:220 +0x390\n","pid":1209,"source":"zedbox","time":"2020-09-22T07:38:28.755503915Z"}
```
and EVE is rebooting due to zedbox crash.

It seems, that we should use Warn instead of Fatal inside Maybe function.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

2020-09-22 10:11 UTC, eriknordmark requested changes
If the RefCount management is incorrect the something is utterly broken and needs to be urgently fixed. Papering over the problem by not Fatal is the wrong thing to do.

Note that the code uses Has*Ref booleans to track which objects it has references against. Something must be wrong around that handling or in handleverifier.go itself to get the refcount wrong.

The "Maybe" refers to this only removing once the refcount reaches zero. Doesn't mean "ignore serious bugs".

2020-09-22 15:44 UTC, mydatascience commented
Actually this container doesn't run (stuck on creating volume and then provides the error) 
 https://github.com/lf-edge/eden/blob/master/tests/phoronix/image/Dockerfile

2020-09-22 15:56 UTC, eriknordmark commented
> Actually this container doesn't run (stuck on creating volume and then provides the error)
> https://github.com/lf-edge/eden/blob/master/tests/phoronix/image/Dockerfile

Is it uploaded to docker hub? I just want to deploy it manually.

2020-09-22 16:06 UTC, mydatascience commented
docker://itmoeve/phoronix-test:1.0

2020-09-23 08:35 UTC, giggsoff commented
It looks like race condition. Cas client take a time, so we need to lookup new status of blob inside doUpdateContentTree. This is my observation.

2020-09-23 15:25 UTC, eriknordmark commented
> It looks like race condition. Cas client take a time, so we need to lookup new status of blob inside doUpdateContentTree. This is my observation.

The cas ingest path can take an unbounded amount of time. But I don't see the code manipulating the VerifyImageConfig after that completes.

2020-09-23 15:51 UTC, giggsoff commented
I mean `HasVerifierRef` value and moving into `MaybeRemoveVerifyImageConfig` branch which leads to fatal in my first comment.

2020-09-24 07:08 UTC, eriknordmark commented on pkg/pillar/cmd/volumemgr/updatestatus.go
> +				refreshedBlob = loadedBlob // use new one if not exists
That is very suspect. If it doesn't exist that means it disappeared while ingestion happened, and in that case you have nothing to do

2020-09-24 07:09 UTC, eriknordmark reviewed
This code is all changed in master yesterday. Can you check if master is still unstable.
It gets a list of shas back from the worker doing the ingest and then looks up the shas. That might have accidentally fixed this issue as well.

2020-09-24 07:49 UTC, giggsoff commented
Strange, but the error not gone.
Can we add something like this:
```
diff --git a/pkg/pillar/cmd/volumemgr/handleverifier.go b/pkg/pillar/cmd/volumemgr/handleverifier.go
index a47d2ee51..91e285125 100644
--- a/pkg/pillar/cmd/volumemgr/handleverifier.go
+++ b/pkg/pillar/cmd/volumemgr/handleverifier.go
@@ -84,6 +84,11 @@ func MaybeRemoveVerifyImageConfig(ctx *volumemgrContext, imageSha string) {
                        imageSha)
                return
        }
+       if m.Expired {
+               log.Warnf("MaybeRemoveVerifyImageConfig: already Expired for %s",
+                       imageSha)
+               return
+       }
        if m.RefCount == 0 {
                log.Fatalf("MaybeRemoveVerifyImageConfig: Attempting to reduce "+
                        "0 RefCount. Image Details - Name: %s, "+

```
It works for me, but also discussible.

2020-09-24 12:02 UTC, eriknordmark commented on pkg/pillar/cmd/volumemgr/handleverifier.go
> +	if m.Expired {
The fact that this solves it is indicating something has a pointer to a blobStatus after having called MaybeRemoveVerifyImageConfig, and that blobStatus is stale.
I can't find such a location in the code...

2020-09-24 21:26 UTC, mydatascience commented
To replicate the issue: 
       ```
     git clone https://github.com/lf-edge/eden.git/
            cd ./eden
            make clean
            result=""
            q=1
            while [ "$result" == "" ]
            do
                    result=$(curl https://registry.hub.docker.com/v2/repositories/lfedge/eve/tags?page=$q | jq -r '."results"[]["name"]' | grep kvm-amd64 | head -1)
                    q=$((q + 1))
            done
            result2=${result%-kvm-amd64}
            echo $result2 
            export RESULT2=$result2
            

            make build
            ./eden config add default
            ./eden config set default --key eve.tag --value=$result2  
            ./eden setup
            ./eden start
            ./eden eve onboard
            make build-tests
            ./eden test tests/phoronix/ -v debug -a="benchmark=pts/coremark-1.0.0"
```

`./eden pod ps `  - command that shows container status... displays the error in some time. should be running but has something like 
```
NAME    IMAGE                           UUID                                    INTERNAL        EXTERNAL                STATE(ADAM)     LAST_STATE(EVE)
app1    itmoeve/phoronix-test:1.0       5111ebad-ba29-4e4d-aae7-b536f4e43d72    -:80            10.138.15.225:8027      IN_CONFIG       CREATING_VOLUME: [description:"PrepareContainerR
ootDir: Could not create snapshot af0b7a38-4f00-4aaf-ae44-1cbed77f5c08#0.container. CreateSnapshotForImage: could not unpack clientImageObj 6e09525b-7b52-4f59-a3f5-7eae0651f0b2-itmoeve
/phoronix-test@sha256:58c66678b6cac8f458f0f8b7a951d71f592367d5d8f1f3f7c87db09c2a60cfd4: UnpackClientImage: unable to unpack image: 6e09525b-7b52-4f59-a3f5-7eae0651f0b2-itmoeve/phoronix
-test@sha256:58c66678b6cac8f458f0f8b7a951d71f592367d5d8f1f3f7c87db09c2a60cfd4: failed to extract layer sha256:58c66678b6cac8f458f0f8b7a951d71f592367d5d8f1f3f7c87db09c2a60cfd4: failed t
o get stream processor for application/vnd.lfedge.disk.layer.v1+raw: no processor for media-type: unknown\n\n" timestamp:{seconds:1600982332 nanos:530971357}]
```

2020-09-25 16:57 UTC, giggsoff commented
As I mention https://github.com/lf-edge/eve/pull/1488#issuecomment-698975239 problem was in the Image which have two layers with the same sha. I added check for this into the `getBlobChildren` function.

2020-09-25 19:28 UTC, eriknordmark commented
> As I mention [#1488 (comment)](https://github.com/lf-edge/eve/pull/1488#issuecomment-698975239) problem was in the Image which has two layers with the same sha. I added the check for this into the `getBlobChildren` function.

I think the right place for a fix is in lookupBlobStatuses - it should return pointers to the same object when the sha is repeated and currently it returns pointers to different copies of BlobStatus for the same sha.

2020-09-25 22:34 UTC, eriknordmark reviewed
A fix is in https://github.com/lf-edge/eve/pull/1488/commits/97a53137897560e0f6cc383ac62e198ece5f4e1a

Will pull that into master when the build completes.
Thus we don't need this; don't know the impact on other assumptions if we exclude the duplicate shas; @deitch intent was to keep them in place.

2020-09-26 10:13 UTC, giggsoff commented
Thanks for solving the problem!

2020-09-26 10:13 UTC, closed without merging