containerd 1.4.1 ; openssh client in sshd
lf-edge/eve pull request #1546
Opened 2020-10-08 07:49 UTC by deitch

Two changes:

* bumps the `linuxkit/sshd` version to the latest. The only real difference is that this one includes `openssh-client` package, so you can `ssh` from within the device, as well as `scp` from and to the device
* bumps the `linuxkit/containerd` version to the latest. This bumps the containerd version to 1.4.1, which has better memory management (among other things)

Unclear if this will resolve the "many goroutines" question, but it is something we have wanted to do anyways.

2020-10-08 08:16 UTC, deitch commented
I don't understand why this is failing. Well I do, because it is looking for a signed version of `linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64`, which doesn't exist; only `linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f` (without the `amd64`) does exist.

But why is it trying to get `linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64` (with `-amd64`)? The change to the hash exists only in one file `images/rootfs.yml.in`, and that one has the right tag.

@rvs do you understand this build process?

here are the relevant lines from CI:

```
patching file images/rootfs-kvm.yml.in.sed (read from images/rootfs.yml.in)
./tools/makerootfs.sh images/rootfs-kvm.yml /home/circleci/project/dist/amd64/installer/rootfs-0.0.0-pull_1546-1fd4fb12-kvm-amd64.squash squash
Extract kernel image: lfedge/eve-new-kernel:b3f036b5a6acb7660eaafedc58a8cbbe0de61cbe-amd64
Pull image: lfedge/eve-new-kernel:b3f036b5a6acb7660eaafedc58a8cbbe0de61cbe-amd64
Add init containers:
Process init image: linuxkit/init:v0.5-amd64
WARN[0002] Error getting targets/rolf: valid signatures did not meet threshold for targets/rolf 
WARN[0002] targets/justin metadata is nearing expiry, you should re-sign the role metadata 
Pull image: docker.io/linuxkit/init:v0.5-amd64@sha256:3af573658bd0a42e497f7a00b9541830d3145b4c7df64bdea482c910a0ca9f98
Process init image: linuxkit/runc:f79954950022fea76b8b6f10de58cb48e4fb3878-amd64
ERRO[0004] Metadata for targets/justin expired          
WARN[0004] Error getting targets/justin: targets/justin expired at Sun Aug 16 13:47:33 +0100 2020 
ERRO[0004] Metadata for targets/riyaz expired           
WARN[0004] Error getting targets/riyaz: targets/riyaz expired at Mon May 25 15:32:34 -0700 2020 
WARN[0004] Error getting targets/rolf: valid signatures did not meet threshold for targets/rolf 
Pull image: docker.io/linuxkit/runc:f79954950022fea76b8b6f10de58cb48e4fb3878-amd64@sha256:879748f7ed03b51f562022b73f964f90b893ca0ba269c84e7dd4d485afefdaf0
Process init image: linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64
ERRO[0006] Metadata for targets/justin expired          
WARN[0006] Error getting targets/justin: targets/justin expired at Sat Sep 19 21:27:19 UTC 2020 
ERRO[0006] Metadata for targets/riyaz expired           
WARN[0006] Error getting targets/riyaz: targets/riyaz expired at Sat Jun 6 08:35:43 -0700 2020 
WARN[0006] Error getting targets/rolf: valid signatures did not meet threshold for targets/rolf 
FATA[0006] Failed to build init tarball from linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64: Could not pull image linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64: Trusted pull for linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64 failed: No valid trust data for a4aa19c608556f7d786852557c36136255220c1f-amd64 
```

2020-10-08 20:12 UTC, rvs requested changes

2020-10-08 20:12 UTC, rvs commented on images/docker-compose.yml.in
> +        image: linuxkit/sshd:666b4a1a323140aa1f332826164afba506abf597
why are you changing this -- but even if you have a good reason (unless it is somehow related to containerd) I'd rather discuss it in a separate PR

2020-10-08 20:33 UTC, rvs commented
Hey @deitch a few answers:

>  don't understand why this is failing. Well I do, because it is looking for a signed version of linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64, which doesn't exist; only linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f (without the amd64) does exist.

Au contraire -- it seems that on my end -- I have no trouble pulling both:
```
$ docker pull linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64
...
Status: Downloaded newer image for linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64
docker.io/linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64
```

That said -- the whole "trust data" thing needs to be looked at because I see it is failing the same way for me.

> But why is it trying to get linuxkit/containerd:a4aa19c608556f7d786852557c36136255220c1f-amd64 (with -amd64)? The change to the hash exists only in one file images/rootfs.yml.in, and that one has the right tag.

We relying on explicit architecture tagging to make sure we can assemble ARM64 images on x86 host. Hence tools/parse-pkgs.sh has logic to add that to the actual yaml it generates for the build.

2020-10-09 04:18 UTC, deitch commented
Ah that explains it. The official linuxkit images are signed only once, at the multiarch manifest level. So only `abcdef1234` is signed, and not `abcdef1234-amd64`, since the first includes the hash for the second which includes the hashes for each layer. It is the same reason it doesn't sign the hash for each layer.

2020-10-09 04:20 UTC, deitch commented
When you pull `abcdef1234`, it automatically resolved it to `abcdef1234-amd64` when you are on amd64. 

I think you are saying, "that's nice, but I want to assemble for arm64, if I choose to do so, even if I am on amd64." Is that right?

I had thought lkt had an option for that, but if not, we certainly can add it. Is that what you were after?

2020-10-09 04:33 UTC, rvs commented
> I think you are saying, "that's nice, but I want to assemble for arm64, if I choose to do so, even if I am on amd64." Is that right?

yes

> I had thought lkt had an option for that, but if not, we certainly can add it. Is that what you were after?

well, we have that option today ;-)

the problem is -- linuxkit is somehow screwing up that trust thing again -- as I noted I have no problem fetching that -amd64 image via Docker CLI alone

I think we need to get to the bottom of what's wrong with linuxkit

2020-10-09 04:34 UTC, rvs commented
Sorry @deitch -- missed this:

> Ah that explains it. The official linuxkit images are signed only once, at the multiarch manifest level. So only abcdef1234 is signed, and not abcdef1234-amd64, since the first includes the hash for the second which includes the hashes for each layer. It is the same reason it doesn't sign the hash for each layer.

welp -- then linuxkit, indeed, needs to be updated

2020-10-09 06:09 UTC, deitch commented
You are using the "implicit API" here. Sure, the amd64 image underlying `abcd1234` is `abcd1234-amd64`, but it doesn't have to be, and there are some areas where it isn't (luckily, eve doesn't need any of those for now), and it might change in the future. The only thing guaranteed is:

- `abcd1234` is multi arch
- `abcd1234` is signed

You are saying that lkt needs an explicit api to get at those images per platform. Definitely agreed.

2020-10-09 09:15 UTC, deitch commented
As discussed offline, what we _really_ are trying to do is use lkt to build an image for arm64 while on amd64 (or vice-versa). We made it happen by "hacking" at the image tags, which is the "implicit API" represented above. But that API was never fully supported, e.g. you cannot rely on the image tag for one arch being "image tag for multiarch with `-<ARCH>` appended, and lkt doesn't sign the arch-specific images, only the manifest.

The right solution is to get lkt to support `lkt build --arch arm64` and it will build for arm64, no matter what you are on.

We are going to leave this open until we get that support into linuxkit, which I am working on.

2020-10-10 03:11 UTC, rvs commented
Thanks @deitch -- waiting for upstream linuxkit fix then -- in the meantime shouldn't we close this PR?

2020-10-11 11:18 UTC, deitch commented
Nope, we can leave it open. The actual hash version won't change; just the linuxkit build tool.

I already am engaged in conversations about how that should look.

2020-10-22 02:02 UTC, rvs commented
I am super confuse by the latest changes in this PR @deitch ;-)

2020-10-22 03:17 UTC, deitch commented
Don't worry about it. This will remain open until we can get the lkt cross build in place. 

Short form is that it updated to latest:

containerd: for 1.4.1
sshd: for ssh client
init: for logging features

2020-11-11 19:45 UTC, deitch commented
I removed the sshd update, based on the work @rvs did on #1640 . So this is just updates to `linuxkit/init` and `linuxkit/containerd`. 

Also I manually signed those packages, so this will pass, until cross-arch building works in linuxkit.

2020-11-11 19:57 UTC, rvs approved these changes
LGTM! Thanks @deitch -- lets see Eden and Ring0 results now

2020-11-11 22:00 UTC, eriknordmark approved these changes
LGTM

2020-11-11 22:18 UTC, merged