Fixing content tree state in info message
lf-edge/eve pull request #1550
Opened 2020-10-09 11:03 UTC by zed-rishabh

EVE shouldn't report state ```Delivered``` if we get an error while loading the content tree in CAS.

2020-10-09 18:24 UTC, rvs approved these changes
LGTM. @eriknordmark ?

2020-10-09 22:33 UTC, eriknordmark requested changes
Rishab, as I suggested on slack you were going to redo this and instead change the mapping in func (state SwState) ZSwState() to account for how the controller and UI interprets their smaller set of states.
That enables us to later extend the set of states in the API aka ZSwState.

2020-10-12 13:03 UTC, eriknordmark reviewed
LGTM.
Since this will not apply to application instances, volumes, and content-trees can you verify that the UI shows all three of them correctly?

2020-10-12 13:38 UTC, zed-rishabh commented
> LGTM.
> Since this will not apply to application instances, volumes, and content-trees can you verify that the UI shows all three of them correctly?

Content-tree and application instance state are showing correctly now but the run state of the volume instance is still incorrect. I am looking at it.

2020-10-12 15:42 UTC, eriknordmark approved these changes
LGTM

2020-10-12 20:01 UTC, merged