[WIP] Introduce /config/server.override; commit to it if/when test complete
lf-edge/eve pull request #1566
Opened 2020-10-15 22:15 UTC by eriknordmark

This code enables the building of special images which will try to move the device to a different server.
It requires a special image to be build e.g., with this code added at the top of device-steps.sh:
echo "$(date -Ins -u) Try switching to different server"
echo "zedcloud.xyzzy.zededa.net" >/config/server.override

If the device is onboarded and manages to get config from that server, then it will commit that to /config/server.
If not, the image will fail with Exceeded time to talk to server, and fallback.

2020-10-15 22:22 UTC, rvs requested changes
Hey @eriknordmark -- I think we need to talk in much greater details about usecase this is intended for and ramifications of this. I have a few concerns -- but I'd rather discuss them in a more fluid forum first before starting to comment on the PR.

Let me know what forums you'd prefer -- I'd imagine that we probably need to annouce it on eve-tsc@ as well -- since this looks really big (conceptually).

2020-10-16 06:52 UTC, deitch commented
Can we add documentation about the use case? I am not sure what "try to move the device to a different server" means, and why/when we would want it.

2020-10-16 12:22 UTC, eriknordmark commented
Added more descriptive text. Note that this is a short-term approach. The redirection service is something we will be looking into as a longer term approach.

2020-10-16 12:42 UTC, gkodali-zededa approved these changes
LGTM
Interim approach looks reasonable to me.

2020-10-19 03:53 UTC, rvs commented
Hey @eriknordmark -- I still would like to get a chance to discuss this first -- lets add it to the huddle we're having on Tue before we merge this. Sounds good?

2020-10-19 06:30 UTC, deitch commented
Let me try to see if I understood it. 

We want the ability to move an edge node from controller A to controller B. But, we must be able to do it without:

* physically accessing the device
* ssh into the device (either manual or automated)

In order to do it, we are:

1. Installing a new image and rebooting
1. The new image writes to `/config/server.override`
1. All of the services (those that talk to the controller) need to be changed to read `server.override` if it exists, or fall back to `server`
1. After boot into the new image, `nodeagent` moves `server.override` to `server`
1. Possibly another boot is necessary?

This seems pretty heavy and prone to failure at multiple points along the line - images, reboots, changing all of the eve services to read multiple files, logic to handle if the contents of one file are the same name as another.

Is it really harder to just have a redirect service? I see two ways this can be:

* actual redirect from controller A to controller B (literally a 301 or 302). Of course, this requires A to be up any time a device boots, but that isn't bad, and even can lead to a much better design pattern: a redirect service that everyone talks to, with the actual controllers being distinct.
* config update. Have controller A send a config update to device to say, "I am handing you off to controller B, goodbye". nodeagent updates `/config/server`, reboots, done.

Either of these seem much lighter and easier than special images with custom device-steps and installs and "is the content of this file already the same as that file" and multiple files `server` and `server.override`.

Am I missing something fundamental?

2020-10-19 11:24 UTC, eriknordmark commented
> 5\. Possibly another boot is necessary?

No additional reboot is needed.

2020-10-19 11:29 UTC, eriknordmark commented
> Is it really harder to just have a redirect service? I see two ways this can be:
> 
> * actual redirect from controller A to controller B (literally a 301 or 302). Of course, this requires A to be up any time a device boots, but that isn't bad, and even can lead to a much better design pattern: a redirect service that everyone talks to, with the actual controllers being distinct.
> * config update. Have controller A send a config update to device to say, "I am handing you off to controller B, goodbye". nodeagent updates `/config/server`, reboots, done.
> 
> Either of these seem much lighter and easier than special images with custom device-steps and installs and "is the content of this file already the same as that file" and multiple files `server` and `server.override`.
> 
> Am I missing something fundamental?

Time frame is one thing you are discounting. @raghu needs a solution which can be used in a few weeks. Agreeting on the requirements for the redirection service (e.g., is a residual dependency on "old" a deal breaker or not?), implementing and deploying it all the way to production will take longer than that.

I don't think a "I am handing you off to controller B, goodbye" approach satisfies the "no brick" requirement. The if there is a new config which can potentially brick the device it needs to be tested with fallback. Thus such an approach would look a far bit like this interim approach. 

If it turns out that we agree that is the long-term redirection approach we can evolve the code in this PR.

2020-10-19 20:07 UTC, eriknordmark commented
We will manage this by keeping this code in this branch. No need to put in master.

2020-10-19 20:07 UTC, closed without merging