io_uring: Merge backported io_uring support into the master branch
lf-edge/eve pull request #1627
Opened 2020-11-07 10:40 UTC by temerkhanov

- Backport io_uring from kernel 5.9 to new-kernel
- Enable io_uring support in xen-tools
- Enable io_uring support in EVE
- Add misc kernel fixes

2020-11-07 21:13 UTC, rvs requested changes
Hey @temerkhanov -- thanks for putting it together. Please answer the questions about the individual patches re-jiggering.

On top of that, I would still like this to soak much more before we make any of this official. To this end:
  1. I see that you updated the new-kernel which is exactly the right thing to do
  2. I am obviously uneasy when it comes to `thread -> io_uring` change in kvm.go. The problem is that if we merge your PR as-is our master will break (since the default build is kernel and not new-kernel). So perhaps, one way to have our cake and eat it too is for kvm.go to test for the kernel version and if it is 5.4.72 or higher default to io_uring and if it isn't default to threads. I am open to other ideas as well.

2020-11-07 21:14 UTC, rvs commented
Oh, and one more question: can we kill storage branch now or do you still want to use it for something @temerkhanov ?

2020-11-09 04:59 UTC, temerkhanov commented on pkg/new-kernel/patches-5.4.x/0001-swiotlb-xen-use-vmalloc_to_page-on-vmalloc-virt-addr.patch
> -From f5f4de59377afdd9a80e0f47df109eacf427c203 Mon Sep 17 00:00:00 2001
Yes, an updated version of this patch is included in 5.4.72

2020-11-09 05:00 UTC, temerkhanov commented on pkg/new-kernel/patches-5.4.x/0011-adding-page-coherent-patch.patch
> -From 1f1182bf84ec7a6d1ec74c56fccd66ff013077af Mon Sep 17 00:00:00 2001
Yes, an updated version of this patch is included in 5.4.72

2020-11-09 05:00 UTC, temerkhanov commented on pkg/new-kernel/patches-5.4.x/0015-Use-chip-data-for-storing-per-IRQ-XEN-data-pointer.patch
> -From: Thomas Gleixner <tglx@linutronix.de>
Yes, this patch is included in 5.4.72

2020-11-10 20:49 UTC, rvs approved these changes
Once small nit -- LGTM otherwise

2020-11-10 20:49 UTC, rvs commented on pkg/pillar/hypervisor/kvm.go
> +	if major >= 5 && minor >= 4 && patch >= 72 {
Two suggestions here @temerkhanov 
   1. could you please turn 5.4.72 into something like a `const minUringKernelVersion = [5, 4, 72]` at the top of this file (feel free to come up with better name)?
   2. let's make the comparison real (jut to make sure that should we upgrade to 5.10.0 this check will still pass)?

2020-11-11 22:34 UTC, rvs approved these changes
LGTM

2020-11-12 02:34 UTC, merged