Printing reboot-reason to /dev/console
lf-edge/eve pull request #1724
Opened 2020-12-08 07:08 UTC by adarsh-zededa

Signed-off-by: adarsh-zededa <adarsh@zededa.com>

2020-12-08 07:31 UTC, eriknordmark reviewed
I think we should (also) print it from agentlog.go and watchdog-report.sh when we go down because at that point in time we wait before the actual reboot. Here on restart we end up dumping lots of other output on the console whether from linuxkit or from diag

2020-12-08 22:15 UTC, rvs approved these changes
LGTM

2020-12-09 00:33 UTC, eriknordmark requested changes
Please add the printing when the device is about to reboot per my comment

2020-12-09 13:40 UTC, adarsh-zededa commented
> Please add the printing when the device is about to reboot per my comment

Done.

2020-12-10 17:11 UTC, eriknordmark commented on pkg/pillar/scripts/device-steps.sh
> +  if [ -f $FIRSTBOOTFILE ]; then
Odd indentation and elif is the normal thing to do in cases like this.

2020-12-10 17:15 UTC, eriknordmark approved these changes
If shellcheck didn't complain I guess the shell identation is ok.

2020-12-10 17:26 UTC, eriknordmark commented
Some ring1 failures which seem completely unrelated so pulling this.

2020-12-10 18:25 UTC, merged