workflows: build both KVM and Xen before push
lf-edge/eve pull request #1781
Opened 2021-01-13 19:26 UTC by dkionka

Avoid the mismatch when KVM builds and pushes, but then Xen fails to build.

2021-01-13 19:59 UTC, dkionka commented
Note that the checks run for the PR not use this file, so the tests are meaningless. The PR workflow uses .github/workflows/pulls.yml, but I changed .github/workflows/publish.yml. That will only be used after the merge. I believe it will work, but the automated builds cannot pre-test it.

2021-01-13 20:04 UTC, rvs requested changes
Would be nice to see how easy it maybe not to rebuild everything twice @dkionka

2021-01-13 20:04 UTC, rvs commented on .github/workflows/publish.yml
> +        # do not push either unless both can build
I like the way this is going, but this current approach will increase our build time by ~40%.

Can you please look into whether for publish action specifically we can get away with NOT removing dist in between the steps (and possibly tweaking the eve build target)?

2021-01-13 20:41 UTC, dkionka commented
The new version reduces thrashing, but still adds 1 minute.

2021-01-13 21:59 UTC, dkionka commented
We could use LINUXKIT_PKG_TARGET='push --nobuild', but the extra minute comes from all the overhead every time you run make. The build is all cached, so you do not save anything with the option, and it seems less robust.

2021-01-14 04:02 UTC, rvs approved these changes
LGTM

2021-01-14 04:52 UTC, kalyan-nidumolu commented
@dkionka - Thanks for Fixing this. Can you also add a separate tags for Xen and KVM images when pushing to dockerhub?

snapshot-xen-amd64 --> For Latest Xen images
snapshot-kvm-amd64 --> For Latest KVM images
snapshot-amd64 --> For Latest xen images ( 2 tags for latest xen images - for backward compatibility with tools)

This would make it much simpler for tools to pull the image they want.

2021-01-14 05:25 UTC, rvs commented
@kalyan-nidumolu this will be pretty difficult to do reliably (since we have to support both ARM and x86) so I'm not sure how much time needs to be spent on this given that our test infra seems to be doing fine

2021-01-14 05:25 UTC, merged