Handle azure oci manifest
lf-edge/eve pull request #1792
Opened 2021-01-16 19:44 UTC by adarsh-zededa

Description of this issue (by @deitch):
AzureContainerRregistry actually sanely implements the OCI distribution spec, whereas Docker Hub does not. We ended up relying on the DHub implementation.

when you want to pull a blob, you use endpoint /v2/<name>/blobs/<digest>
when you want to pull a manifest, you use endpoint /v2/<name>/manifests/<reference>
What do you do when you have a sha256 but do not know if it is a manifest-type (manifest or index) or something else (layer or config)? The sane thing to do is have it always available via /blob, since a blob is a blob is a blob.

Docker Hub does not do that, it returns an error if what you are requesting is a manifest; Azure returns the content.

Signed-off-by: adarsh-zededa <adarsh@zededa.com>

2021-01-17 01:37 UTC, rvs approved these changes
Please fix yetus complaints -- LGTM otherwise

2021-01-17 08:52 UTC, deitch commented
It also is getting build errors.

2021-01-17 08:56 UTC, deitch requested changes
The logic looks pretty good, and hats off, it looks a lot cleaner than before! The only changes I would request are in the logging, which might look confusing now.

2021-01-17 08:56 UTC, deitch commented on libs/zedUpload/ociutil/oci.go
> +		logrus.Infof("PullBlob(%s): unable to fetch manifest. %s", image, err.Error())
With the change, this log line is confusing, and will look like an error. Might want to add a line before like, "trying to get <ref> as manifest", and then this line can be, "unable to fetch <ref> as manifest, trying as blob", etc.

2021-01-18 18:48 UTC, deitch approved these changes

2021-01-19 03:05 UTC, rvs approved these changes
LGTM, but seems like Eden is failing -- I've re-triggered it -- but if it fails again you'll have to look into this @adarsh-zededa

2021-01-19 17:04 UTC, merged