Create dependabot.yml, update Dockerfile versions
lf-edge/eve pull request #1810
Opened 2021-01-22 01:51 UTC by dkionka

These were generated by Dependabot PRs:
Bump lfedge/eve-alpine from 5.16.0 to 5.19.0 in /pkg/alpine
Bump alpine from 3.8 to 3.13.0 in /pkg/guacd
Bump alpine from 3.6 to 3.13.0 in /pkg/qrexec-dom0
Bump alpine from 3.6 to 3.13.0 in /pkg/qrexec-lib
Bump alpine from 3.8 to 3.13.0 in /pkg/watchdog
Bump alpine from 3.8 to 3.13.0 in /pkg/wlan
Bump alpine from 3.12 to 3.13.0 in /pkg/wwan
Bump alpine from 3.7 to 3.13.0 in /pkg/xen

Manual changes:
- downrev alpine in pkg/qrexec-dom0/Dockerfile.in
- fix COPY --from with /var symlink
- replace libelf-dev with libelf

2021-01-22 02:22 UTC, dkionka commented
Dependabot does not do the full version update that we need -- if you update the base OS image, you also need to update the package versions that are hardwired. But several Eve packages do not hardwire the package versions, so we might as well take advantage of Dependabot, since it is built into GitHub.

2021-01-22 19:09 UTC, dkionka commented
I recommend having this .github/dependabot.yml file checked in, but not enabling Dependabot in the reference lf-edge tree. It can then be used in any fork where it can be reviewed and tweaked before the user submits the PR as I am doing here.

I enabled Dependabot in my fork by enabling it in **Settings → Security & analysis**:
https://github.com/dkionka/eve/settings/security_analysis
Then I open: **Insights → Dependency graph → Dependabot**
https://github.com/dkionka/eve/network/updates

Every time I update the .yml it re-runs the analysis. If a version needs to be updated it generates a PR:
https://github.com/dkionka/eve/pulls?q=
Those PRs are on branches that you can find with:

> $ git branch -a | grep dependabot/
  remotes/origin/dependabot/docker/pkg/alpine/lfedge/eve-alpine-5.19.0
  remotes/origin/dependabot/docker/pkg/guacd/alpine-3.13.0
  remotes/origin/dependabot/docker/pkg/qrexec-dom0/alpine-3.13.0
  remotes/origin/dependabot/docker/pkg/qrexec-lib/alpine-3.13.0
  remotes/origin/dependabot/docker/pkg/watchdog/alpine-3.13.0
  remotes/origin/dependabot/docker/pkg/wlan/alpine-3.13.0
  remotes/origin/dependabot/docker/pkg/wwan/alpine-3.13.0
  remotes/origin/dependabot/docker/pkg/xen/alpine-3.13.0

I then cherry-pick from all the branches and run a local test build. Finally I squash all of the cherry-picks and create my own PR for lf-edge.

2021-01-22 21:47 UTC, rvs requested changes
Hey @dkionka -- this PR needs to be split in two -- one part needs to be simply mechanics for enabling dependabot and that could be merged pretty quickly.

The bumping of Alpine dependencies will be a huge undertaking and needs to dovetail into your other work of creating a full bill of materials of all packages and versions that we're using. Until that is done -- I don't feel comfortable doing random bumps.

2021-01-22 23:02 UTC, dkionka commented
I made this the .yml only change, since I explain how to use it above, and I moved the Dockerfile changes to: https://github.com/lf-edge/eve/pull/1817

2021-01-23 02:20 UTC, rvs commented
Awesome @dkionka -- one last thing -- can you please move the explanation you provided in a PR to be a section in this doc https://github.com/lf-edge/eve/blob/master/docs/CI-CD.md -- just add it at the very bottom, ok?

2021-01-25 18:41 UTC, dkionka commented
> Awesome @dkionka -- one last thing -- can you please move the explanation you provided in a PR to be a section in this doc https://github.com/lf-edge/eve/blob/master/docs/CI-CD.md -- just add it at the very bottom, ok?

I moved it to to the doc.

I made it more generic because I am also working on scripts to list package versions to change, and that will be a 2nd section under maintaining Dockerfiles.

2021-01-25 20:15 UTC, dkionka commented
This is the followup change to add version check scripts: https://github.com/lf-edge/eve/pull/1825

2021-01-27 19:51 UTC, dkionka commented
I fixed the yetus errors, so this should be ready to be merged.

2021-01-29 02:56 UTC, rvs approved these changes
LGTM

2021-01-29 02:56 UTC, merged

2021-02-01 17:40 UTC, dkionka commented
I thought that this would stay unused unless you enabled dependabot, but it is creating branches and generating PRs like https://github.com/lf-edge/eve/pull/1847 .

2021-02-01 21:48 UTC, rvs commented
That's fine -- we may as well turn it on -- the bigger question is coordinating flag days for upgrades @dkionka