xen-start fixes for domain reboot
lf-edge/eve pull request #1911
Opened 2021-02-16 18:04 UTC by petr-zededa

During restart of domain (initiated by reboot from inside of DomU) it changes the ID, so we need to take care of it in `xen-start` script.

Signed-off-by: Petr Fedchenkov <petr@zededa.com>

2021-02-16 22:55 UTC, eriknordmark commented
@adarsh-zededa can you take a look.

2021-02-16 23:01 UTC, rvs commented
Honestly, I think at this point this whole thing is "workaround'y" enough so that we should take a step back and perhaps consider if there's a better way. One idea is to hook directly from our go layer into Xen's toolstack, the other is using their newfangled xenfs.

So what do you guys think? An opportunity for a more fundamental refactoring?

2021-02-17 20:35 UTC, petr-zededa commented
What I also find here, we use `xl list "${1:- }"` which is actually equals to `xl list  ` in case of empty output from domID.

I will take a look onto libxl bindings. So far, the developers are optimistically [writing](https://github.com/xen-project/xen/tree/master/tools/golang/xenlight#about) that they are experimental.

2021-03-20 08:16 UTC, eriknordmark requested changes
@petr-zededa two PRs have gone into xen-start the last week.
Do you have a test case we can use to see if this issue has been resolved by them?
I suspect so but I don't know what the user-visible bug was which made you submit this PR.

2021-03-22 15:14 UTC, petr-zededa commented
Seems, that it try to fix the same things

2021-03-22 15:14 UTC, closed without merging