Should explicitly specify what arches we want to build eve packages for
lf-edge/eve pull request #2102
Opened 2021-05-26 13:40 UTC by deitch

We use `make eve` in the root to call `linuxkit pkg build` with the `build.yml` from `pkg/eve/build.yml`. That does not specify explicitly which arches are supported, so a future call to `pkg build` will try to build for lots of things that might or might not suit us.

This makes it explicit.

cc @vmlemon @rvs 

Related to [this](https://github.com/lf-edge/eve/pull/2061#issuecomment-848777037)

2021-05-27 21:59 UTC, rvs requested changes
I am actually not convinced this is the right approach @deitch 

Lets think as to what's the happy path here: the happy path is to NOT cross-compile this package ever.

This means that we should probably figure out a way that running linuxkit by default on it only compiles for the architecture we are on. Is there a way to do it @deitch ?

2021-05-27 22:29 UTC, deitch commented
Sure. Just call it as `lkt pkg build <path> --platforms=linux/arm64` or whatever you're in. Stick it in the makefile where we already do that.

2021-05-27 23:25 UTC, vmlemon commented
Hmm, would https://github.com/tonistiigi/xx be of any use to us, for this kind of thing? I stumbled across it, whilst watching some of the DockerCon videos, earlier on.

2021-05-28 00:27 UTC, rvs commented
No, we don't need any of that @vmlemon -- nice find tho

2021-05-28 00:32 UTC, rvs commented
Btw @deitch it sounds like with the explicit invocation of linuxkit you suggested above -- we should close this PR?

2021-05-28 04:19 UTC, deitch commented
Correct. 

How did you find time to watch those videos @vmlemon :-)

2021-05-28 04:33 UTC, deitch commented
Actually I'm going to change that. The explicit platforms invocation is independent of this PR. This PR sets the default for when you do _not_ explicitly set platforms. When you explicitly do - as suggested above - the `arches` part of build.yml is ignored. Consider this a "safety net" for when someone runs it without explicit `platforms` (only do these platforms, not every one linuxkit can think of), as well as good indication / documentation what platforms are supported. 

I would merge this in for those reasons, and then do the explicit `--platforms` to restrict it to just one platform when running.

2021-05-28 07:47 UTC, vmlemon commented
> Correct.
> 
> How did you find time to watch those videos @vmlemon :-)

Copious amounts of coffee, snacks, and planning out which sessions were most interesting, before ending up staying awake until 2am. The time boundaries also kinda-helped, since the videos were just short enough, that the start/end of each overlapped... :)

2021-05-28 19:05 UTC, rvs commented
> Consider this a "safety net"

The problem with looking at it as a safety net @deitch is that it is broken -- attempting to cross-build eve packages (specifically) will result in ether failure or worse yet producing an incorrect container. Both of these are not what I would call a safety net.

Specifically for eve -- it really has to be somehow the platform I'm running on. Which brings me to: it really would be helpful if there was a way to say:

```
arches:
  - self
```

Which would mean that the package is declaring itself to be safe to be built on any architecture as long as cross-compilation is not involved.

2021-05-30 13:45 UTC, deitch commented
> The problem with looking at it as a safety net @deitch is that it is broken

I don't understand why it is broken. It doesn't say, "I will prevent you from building any other arches." If you specify `pkg build --platforms=foo`, it will let you build for `foo`. If you specified `foo`, you are more than smart enough to know that was what you wanted to build.

> attempting to cross-build eve packages (specifically) will result in ether failure or worse yet producing an incorrect container. Both of these are not what I would call a safety net.

If eve cross-building fails, let's fix it. But `pkg build` does what it is expected to:

* if you specified `--platforms`, build for that
* if you did not, build for the "default arches" specified in the file

> arches:
>  - self

I don't see the maintainers agreeing to that. Why would I want to say, "this is safe to build as long as cross-compilation is not involved"?

2021-06-01 14:49 UTC, rvs commented
> I don't understand why it is broken. 

It is broken because running `make eve` with your changes will produce a package with a broken content for non-host arch.

I think we need to discuss it in a more 1-1 way at this point -- since it is clearly that both of us are missing some crucial details here.

2021-06-07 10:56 UTC, rvs commented
Hey @deitch -- shouldn't this be closed in favor of #2115 ?

2021-06-07 12:27 UTC, deitch commented
Nope. This is about what platforms I build for in my current command, not creating an index. Two distinct things.

2022-12-05 10:40 UTC, rouming commented
@deitch do we close this?

2022-12-05 17:07 UTC, closed without merging