explciitly create manifest index
lf-edge/eve pull request #2115
Opened 2021-06-02 12:47 UTC by deitch

The GitHub publish process as it stands today relies on running `linuxkit pkg push` from various places, and assuming it doesn't trounce one another (e.g. two parallel builds that create the multi-arch index at precisely the same time can trounce each other; I have seen it happen).

Further, linuxkit's build process has changed, such that it just builds a manifest index locally and pushes it out, not relying on what is in the registry, so running in parallel will not work going forward. It does that because it is simpler, and one always can rely on `docker manifest` or `manifest-tool` to build indexes.

This PR does the following:

1. Add manifest build targets to `Makefile`
2. Leverage those build targets in `publish.yaml`

### Manifest build targets

The simplest is `manifest-%`, which will try to create a multi-arch index for the provided package. It tries to do it for all provided architectures (arm64, amd64,. riscv64), but is perfectly happy to ignore a missing one.

This is idempotent. You can run `make manifest-eve` a dozen times. All it does is:

1. Find all images with the right name ending in `-<arch>` in docker hub
2. Create and update a local manifest list with those it finds
3. Pushes it out

It also is very fast, as it is just reading manifests; no building or image pulling going on.

The next is `pkgmanifests`, which tries to build for _all_ packages. It does not care what platform you are on (e.g. riscv64 has a smaller set of packages than amd64). It just tries to build indexes for every possible package on every possible arch, and ignores those for which there just isn't an image for that arch.

### Leverage in publish

Adds a new job to `publish.yml` to build manifests for:

1. All packages
2. `lfedge/eve`

This new job has `needs: build`, so it waits until all of them are done.

Since the tasks are idempotent and fast, these will run perfectly fine now, and with planned linuxkit changes. It just happily looks for all arch-specific images on the registry and builds indexes for them.

2021-06-02 12:48 UTC, deitch commented
cc @vmlemon @rvs

2021-06-02 13:00 UTC, deitch commented
Yetus error is a single one about a "too long yaml" line, but this should be the way it is; ignore.

2021-06-02 20:25 UTC, rvs commented
Hey @deitch -- I understand what you're doing here, but I have one conceptual question: from your description it sounds like linuxkit is now completely abdicating from managing multi-arch manifests. That in and of itself seems wrong. Please let me know if my understanding is correct and if it where would be an appropriate place to discuss this.

The reason I'm raising this now is very simple: I think what you've done in the Makefile is great, but I also thinks it belongs (under an explicit command perhaps) in linuxkit and not our Makefile.

2021-06-02 20:26 UTC, rvs requested changes
Marking it Request change for now -- to quickly figure out what to do next with linuxkit side of things.

2021-06-03 10:07 UTC, deitch commented
> from your description it sounds like linuxkit is now completely abdicating from managing multi-arch manifests. That in and of itself seems wrong. Please let me know if my understanding is correct and if it where would be an appropriate place to discuss this

Not precisely. linuxkit itself never actually did it, just passed it off to manifest-tool, then later the embedded library based on manifest-tool. It didn't want to care too much, but it had to because you had to run it on different platforms separately:

1. run on amd64 = build and push pkg on amd64
2. run on arm64 = build and push pkg on arm64
3. run on s390x = build and push pkg on s390x

To make it convenient, we took advantage of how manifest-tool worked to modify it so that

1. run on amd64 = build and push pkg on amd64, push multi-arch index for everything already on the hub
2. run on arm64 = build and push pkg on arm64, push multi-arch index for everything already on the hub
3. run on s390x = build and push pkg on s390x, push multi-arch index for everything already on the hub

The above meant some interesting hackery, and also meant you couldn't run them in parallel, as the index on one could trounce the other. So it was changed:

1. run on amd64 = build and push pkg on amd64
2. run on arm64 = build and push pkg on arm64
3. run on s390x = build and push pkg on s390x
4. run anywhere = push multi-arch index for everything already on the hub

But that still meant you had to run on multiple machines, painful. Which then moved to:

1. run anywhere = 
   1. build pkg on amd64 and output to local cache
   2. build pkg on arm64 and output to local cache
   3. build pkg on s390x and output to local cache
   4. create multi-arch index based on local packages
   5. Push all of the above (very simply) to hub

The index generation became materially simpler. If you did, however, want to do the following:

1. run anywhere = 
   1. build pkg on amd64 and output to local cache
   2. build pkg on arm64 and output to local cache
   3. build pkg on s390x and output to local cache
   5. Push arch-specific images only (very simply) to hub
1. Run elsewhere = create and push index based on what is on the hub

Then you can do the last step with `manifest-tool` or `docker manifest create`, which is what we do here.

Does that explain it?

2021-06-03 18:58 UTC, rvs commented
Hey @deitch -- thanks for a clear expose, but I still don't buy this part of the argument:

> But that still meant you had to run on multiple machines, painful.

Running on multiple machines is still very much a reality. We are never going to converge and have a world where everything is driven by a master buildkit process. Hence, it sounds to me that the same functionality that linuxkit used to have when it comes to updating a manifest may still be useful.

Let me ask you this: what's the downside of having `linuxkit pkg build -m XXX` wher e`-m` will mean update the manifest the way it used to happen?

2021-06-04 08:51 UTC, deitch commented
> Running on multiple machines is still very much a reality. We are never going to converge and have a world where everything is driven by a master buildkit process.

Sort of. Using buildkit and docker context, you can do the actual _build process_ on a remote machine, but all controlled from one central machine. Sort of like Jenkins agents. That is how buildkit now does all of its packages. It still builds natively on each architecture, but instead of, "I have to ssh to each machine, build, login to hub, push, then go back to one machine and create a manifest", it now is, "I go on one machine, run build, and docker automatically goes to all of the various machines and builds, but brings the resulting artifacts back here, so I just have to execute a single command once."

> Let me ask you this: what's the downside of having linuxkit pkg build -m XXX wher e-m will mean update the manifest the way it used to happen?

None that I can think of, other than duplication. If it is just going to replicate something someone easily can do with `docker manifest create` or `manifest-tool`, people will ask why we bother. What's the benefit of doing it via `lkt pkg push manifest` (or whatever syntax) vs just running the other command?

I have been mulling this over for the past week or so. I have struggled to find a solid counter-argument to the above. If we had one, we could justify it.

2021-06-07 10:53 UTC, rvs requested changes
> Sort of like Jenkins agents.

Yeah, but that basically required the kind of setup that is alien to most SaaS CI/CD solutions (including GH actions). It inverts the model and makes build nodes sort of permanent instead of spinning them up on demand. Hence, for now it is simply incongruous with our needs.

> I have been mulling this over for the past week or so. I have struggled to find a solid counter-argument to the above. If we had one, we could justify it.

Ok @deitch -- let me try to resurrect the code in linuxkit first -- if that gets accepted you can update the PR, if it doesn't -- we can always pull it as-is.

2021-06-07 12:26 UTC, deitch commented
Actually, I already created a PR in lkt for it. Let's see what happens with that.

2021-06-07 12:45 UTC, rvs commented
> Actually, I already created a PR in lkt for it. Let's see what happens with that.

Nice! Saves me a few hours ;-) could you please link that PR here?

2021-06-14 11:28 UTC, deitch commented
This no longer is necessary with the latest linuxkit. Now, if you do `lkt pkg push`, it will push whatever images it builds locally, but will build the manifest from _everything_ available in the registry. It becomes idempotent, runnable as many times as you want, from wherever you want.

2021-06-14 11:29 UTC, closed without merging

2021-06-14 19:16 UTC, rvs commented
Yay! Right thing wins! ;-) Thanks for seeing this through