unmount rootfs of containers on doInactivate
lf-edge/eve pull request #2124
Opened 2021-06-08 13:32 UTC by giggsoff

In my experiments with zfs-kvm I see errors 
```
state: PURGING: [description:"doActivate: Failed mount snapshot: 07887c71-2249-4ff7-8a0d-21cb1b804f14#0.container for f416c744-e01f-4b45-8b43-fc1916e01247. Error MountSnapshot: Exception while fetching mounts of snapshot: 07887c71-2249-4ff7-8a0d-21cb1b804f14#0.container. device or resource busy" timestamp:{seconds:1622120958 nanos:489636236}] received in: 2021-05-27T13:09:18.905436106Z
```
It comes when I try to stop and restart container-in-VM.
Seems, we do mount, but do not call unmount on stop of app.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

2021-06-09 22:02 UTC, eriknordmark reviewed
This appears to be the undo operation corresponding to ctx.casClient.MountSnapshot.
Would it make sense to have the cas package do the unmount as well using some new API? Or is that too hard due to the possibility of nested mounts across diskStatusList?

2021-06-12 11:34 UTC, rvs requested changes
I am with @eriknordmark on this one -- I don't think this is the right place for this change. In fact, I vaguely remember containerd APIs having an idiomatic way of doing this -- perhaps @deitch can remember what it was a bit better (and save me the trouble of digging through the `ctr` codebase).

Let's explore that option first before we proceed with this change.

2021-06-15 07:52 UTC, eriknordmark approved these changes
LGTM

2021-06-15 07:58 UTC, deitch commented
We create the rootfs [in eve](https://github.com/lf-edge/eve/blob/62e299b7e6d314b1df8ce56366081e26f65f9648/pkg/pillar/containerd/containerd.go#L284-L315) using [snapshot.Prepare](https://pkg.go.dev/github.com/containerd/containerd@v1.5.2/snapshots#Snapshotter) and [Mount.Mount](https://pkg.go.dev/github.com/containerd/containerd@v1.5.2/mount#Mount.Mount). Should we not be using the parallel [mount.Unmount](https://pkg.go.dev/github.com/containerd/containerd@v1.5.2/mount#Unmount) and [snapshot.Remove](https://pkg.go.dev/github.com/containerd/containerd@v1.5.2/snapshots#Snapshotter) ?

2021-06-15 07:59 UTC, deitch commented
My apologies for responding in so delayed a fashion; way too many GitHub alerts caused me to miss this.

2021-06-15 08:14 UTC, giggsoff commented
@deitch I think it is good idea to not forget to unmount rootfs before mounting it again. 
So it is undo operation for https://github.com/lf-edge/eve/blob/af815eda61fe63ed26bc4996af3a805a7a842989/pkg/pillar/cmd/domainmgr/domainmgr.go#L1202-L1208

Preparation of snapshot involved in the different process as I can see, not in activate/inactivate. Or I miss something?

2021-06-15 08:26 UTC, deitch commented
> I think it is good idea to not forget to unmount rootfs before mounting it again.

No issue with that. I do think we should use the containerd utilities, though, rather than doing it manually.

2021-06-15 09:12 UTC, giggsoff commented
>we should use the containerd utilities

Good point, modified

2021-06-15 14:51 UTC, deitch commented on pkg/pillar/cas/cas.go
> +	UnmountContainerRootDir(rootPath string) error
I really want this to be parallel, so `UnprepareContainerRootDir()`, but that is just so awful, let's leave it as `UnmountContainerRootDir()` 😄

2021-06-15 14:52 UTC, deitch approved these changes
Looks right to me. Do tests cover it?

2021-06-23 00:29 UTC, rvs approved these changes
LGTM. Let it test.

2021-06-23 04:18 UTC, merged