pass grub config file for installer
lf-edge/eve pull request #2303
Opened 2021-10-04 15:33 UTC by giggsoff

The ability to use grub.cfg from config file in case of iso installer.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

2021-10-04 17:35 UTC, eriknordmark requested changes
It doesn't make sense to only look for grub.cfg from a different place; I suspect that customers will (if we ship this) expect EVE to also look for the DevicePortConfig file, authorized_keys, etc in the same place.

Why does it make sense to have the config both inside the ISO and outside? Having only one place would make it a lot simpler for users to understand since if two place they have to understand what takes precendence etc.

2021-10-04 18:28 UTC, giggsoff commented
> It doesn't make sense to only look for grub.cfg from a different place; I suspect that customers will (if we ship this) expect EVE to also look for the DevicePortConfig file, authorized_keys, etc in the same place.

grub configuration I try to pass here is required to properly set options (e.g. eve_install_disk) during installation process. All other options not needed to be passed here, they affect CONFIG partition (copied onto it) on EVE installation (not the process of installation).

> Why does it make sense to have the config both inside the ISO and outside? Having only one place would make it a lot simpler for users to understand since if two place they have to understand what takes precendence etc.

Sorry, cannot understand this part of comment. Both parts points to the same file, but the file is located on partition of USB or just in file on iso (/config.img).

2021-10-04 19:36 UTC, eriknordmark commented
> grub configuration I try to pass here is required to properly set options (e.g. eve_install_disk) during installation process. All other options not needed to be passed here, they affect CONFIG partition (copied onto it) on EVE installation (not the process of installation).

OK. It wlould make sense to add some comments in the code documenting that is why we only copy the grub config.

2021-10-04 19:39 UTC, eriknordmark commented
> Sorry, cannot understand this part of comment. Both parts points to the same file, but the file is located on partition of USB or inside file system inside file on iso (/config.img).

I'm still confused whether there is one partition or two on the USB stick.
If there is only one ISO partition on the USB stick and you are merely adding the loopback mount to be able to apply the grub.cfg then it is fine.

2021-10-04 19:57 UTC, giggsoff commented
> > Sorry, cannot understand this part of comment. Both parts points to the same file, but the file is located on partition of USB or inside file system inside file on iso (/config.img).
> 
> I'm still confused whether there is one partition or two on the USB stick. If there is only one ISO partition on the USB stick and you are merely adding the loopback mount to be able to apply the grub.cfg then it is fine.

We have only one partition on iso. USB (installer_raw) is different option and we have several partitions inside for this case. Yes, PR is only about mounting of file inside iso and obtaining grub.cfg from its filesystem content.

2021-10-04 20:03 UTC, rvs requested changes
This needs a much deeper design review actually. Can we chat about this first before agreeing on the approach here @giggsoff ?

2021-10-05 17:54 UTC, eriknordmark approved these changes

2021-10-06 05:58 UTC, closed without merging