Add onboard cert and onboard key to assets
lf-edge/eve pull request #2355
Opened 2021-10-29 09:05 UTC by deitch

We include a default onboard cert and (embedded in it as the CN) onboarding key. Of course any distro build can change these, but these are the default and often are used.

To make it simple for default users (basic getting started flow), we should include the cert and the key in the assets.

2021-10-31 09:09 UTC, deitch commented
@eriknordmark thanks. Do you know if I got the triggers and cloning right?

2021-11-03 16:24 UTC, rvs requested changes
Sorry to come to this rather late, but... well... actually ;-)

Actually I see no reason for these to be uploaded -- in fact, I'm kind of a big fan of the # of assets to remain as small as possible (actually working on reducing the # for iPXE boots). So what is the real value here @deitch ?

2021-11-04 01:03 UTC, deitch commented
> Sorry to come to this rather late, but... well... actually ;-)

I think "fashionably late" is for parties, not PRs. 😆 

> Actually I see no reason for these to be uploaded -- in fact, I'm kind of a big fan of the # of assets to remain as small as possible (actually working on reducing the # for iPXE boots). So what is the real value here @deitch ?

Think of the user flow when I just want to provision and onboard a device:

1. I take standard vanilla eve right from assets or from the equivalently-tagged docker image
2. I flash it to a device drive, or iPXE it, etc.
3. I go to a controller and it asks me for the serial - which I provide - and the onboard cert or onboard key. And I look and say, "onboard key? where is that? How do I get it?"

Sure, customers and OEMs might (should) very well override it, but they also might have a different build of lots of things. For the basic getting started case - which the assets and hub image are most helpful for - I am missing a piece of information. Telling them, "look in the code" or "go ask in Slack" or "read some docs" doesn't cut it. In any case, we don't have docs that have it, and they could be out of sync, as each build could have its own cert, or at least be changed a few times between builds, which is the definition of an asset that is tied to a release.

In sum: one more step in simplifying basic usage for users. Discussed at length with @kgiori

2021-11-07 16:16 UTC, rvs commented
> I think "fashionably late" is for parties, not PRs. 😆

LOL! But ain't it a party on every PR we have?

> I go to a controller and it asks me for the serial - which I provide - and the onboard cert or onboard key. And I look and say, "onboard key? where is that? How do I get it?"

See, that's where I agree with premise, but disagree with the solution. I think the right solution is to make it visible to the end user during the runtime steps, not hide it inside a set of assets.

I mean -- I'm open to be convinced otherwise -- but for now -- I'd rather not merge it until that happens.

2021-11-07 16:17 UTC, deitch commented
> See, that's where I agree with premise, but disagree with the solution. I think the right solution is to make it visible to the end user during the runtime steps, not hide it inside a set of assets.

I have no issue with that, as long as it is:

* easy for one to find
* tied to the specific release (since each release can change it)

Where would you want it, and how would the process work?

2021-11-23 17:30 UTC, rvs commented
> Where would you want it, and how would the process work?

I'd flip it on you and ask this @deitch -- how do you expect the process you're proposing to work? IOW, ok you've got the certificate published in assets -- now what? How does the workflow for anyone change after that?

2023-08-03 09:35 UTC, rouming commented
@deitch any plans to continue this work or we can close?

2023-08-23 15:37 UTC, rouming commented
Close this due no activity.

2023-08-23 15:37 UTC, closed without merging