[WIP; DO NOT MERGE] update kernel version
lf-edge/eve pull request #2356
Opened 2021-11-01 07:23 UTC by Insei

Update to 5.10.76

Signed-off-by: Aleksandrov Dmitriy <goodmobiledevices@gmail.com>

2021-11-01 16:53 UTC, rvs requested changes
Why is this required @Insei ?

2021-11-01 17:55 UTC, Insei commented
@rvs I want to try updating the kernel and then applying some patches to fix the floating bug:
`Synchronous Exception at 0x000000005EAED180` at creating or rebooting instances.

```
Log list for app 4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70:
Info list for app 4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70:
ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:INITIAL  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760422  nanos:892088603}
atTimeStamp: seconds:1635760422  nanos:892088603

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:RESOLVING_TAG  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760422  nanos:997592491}
atTimeStamp: seconds:1635760422  nanos:997592491

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:DOWNLOAD_STARTED  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760425  nanos:453638447}
atTimeStamp: seconds:1635760425  nanos:453638447

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:VERIFIED  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760429  nanos:63665908}
atTimeStamp: seconds:1635760429  nanos:63665908

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:LOADING  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760434  nanos:103067968}
atTimeStamp: seconds:1635760434  nanos:103067968

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:CREATING_VOLUME  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760434  nanos:566966537}
atTimeStamp: seconds:1635760434  nanos:566966537

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:INSTALLED  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760434  nanos:764592260}
atTimeStamp: seconds:1635760434  nanos:764592260

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:INSTALLED  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760449  nanos:822862075}
atTimeStamp: seconds:1635760449  nanos:822862075

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:INSTALLED  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760450  nanos:238400719}
atTimeStamp: seconds:1635760450  nanos:238400719

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  state:INSTALLED  network:{macAddr:"00:16:3e:00:01:02"  devName:"default"  IPAddrs:"10.11.12.3"  defaultRouters:"10.11.12.1"  dns:{DNSservers:"10.11.12.1"}  ipv4_up:true  localName:"nbu1x2"}  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760450  nanos:417584070}
atTimeStamp: seconds:1635760450  nanos:417584070

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  bootTime:{seconds:1635760450  nanos:850938437}  state:BOOTING  network:{macAddr:"00:16:3e:00:01:02"  devName:"default"  IPAddrs:"10.11.12.3"  defaultRouters:"10.11.12.1"  dns:{DNSservers:"10.11.12.1"}  ipv4_up:true  localName:"nbu1x2"}  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760450  nanos:911611606}
atTimeStamp: seconds:1635760450  nanos:911611606

ztype: ZiApp
devId: 16fd0167-1f7a-4059-bd20-d2c4529f40fc
[0]: ztype:ZiApp  devId:"16fd0167-1f7a-4059-bd20-d2c4529f40fc"  ainfo:{AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  bootTime:{seconds:1635760450  nanos:850938437}  state:RUNNING  network:{macAddr:"00:16:3e:00:01:02"  devName:"default"  IPAddrs:"10.11.12.3"  defaultRouters:"10.11.12.1"  dns:{DNSservers:"10.11.12.1"}  ipv4_up:true  localName:"nbu1x2"}  volumeRefs:"b1d87dce-f92d-4ab5-9778-d07d81de4426"}  atTimeStamp:{seconds:1635760454  nanos:566370669}
atTimeStamp: seconds:1635760454  nanos:566370669

Metric list for app 4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70:
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{}  memory:{}  appMemory:{}
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{}  memory:{}  appMemory:{}
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{}  memory:{}  disk:{disk:"/persist/vault/volumes/b1d87dce-f92d-4ab5-9778-d07d81de4426#0.container"  diskType:"CONTAINER"}  appMemory:{}
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{}  memory:{}  disk:{disk:"/persist/vault/volumes/b1d87dce-f92d-4ab5-9778-d07d81de4426#0.container"  diskType:"CONTAINER"}  appMemory:{}
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{upTime:{seconds:7  nanos:972546119}  total:5  total_ns:5885922613}  memory:{usedMem:693  availMem:407  usedPercentage:63  availPercentage:37}  network:{iName:"default"  txBytes:90  txPkts:1  localName:"nbu1x2"}  disk:{disk:"/persist/vault/volumes/b1d87dce-f92d-4ab5-9778-d07d81de4426#0.container"  diskType:"CONTAINER"}  appMemory:{allocatedMB:1100  usedMB:693}
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{upTime:{seconds:14  nanos:467121955}  total:13  total_ns:13044539975}  memory:{usedMem:693  availMem:407  usedPercentage:63  availPercentage:37}  network:{iName:"default"  txBytes:90  txPkts:1  localName:"nbu1x2"}  disk:{disk:"/persist/vault/volumes/b1d87dce-f92d-4ab5-9778-d07d81de4426#0.container"  diskType:"CONTAINER"}  appMemory:{allocatedMB:1100  usedMB:693}
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{upTime:{seconds:20  nanos:413037544}  total:19  total_ns:19524777581}  memory:{usedMem:693  availMem:407  usedPercentage:63  availPercentage:37}  network:{iName:"default"  txBytes:90  txPkts:1  localName:"nbu1x2"}  disk:{disk:"/persist/vault/volumes/b1d87dce-f92d-4ab5-9778-d07d81de4426#0.container"  diskType:"CONTAINER"}  appMemory:{allocatedMB:1100  usedMB:693}
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{upTime:{seconds:26  nanos:331325139}  total:25  total_ns:25108183672}  memory:{usedMem:693  availMem:407  usedPercentage:63  availPercentage:37}  network:{iName:"default"  txBytes:90  txPkts:1  localName:"nbu1x2"}  disk:{disk:"/persist/vault/volumes/b1d87dce-f92d-4ab5-9778-d07d81de4426#0.container"  diskType:"CONTAINER"}  appMemory:{allocatedMB:1100  usedMB:693}
AppID:"4ca6d78c-d3a1-4e17-8b5c-d09d5f0aae70"  AppName:"curl-acl2"  cpu:{upTime:{seconds:34  nanos:352546824}  total:33  total_ns:33847681638}  memory:{usedMem:693  availMem:407  usedPercentage:63  availPercentage:37}  network:{iName:"default"  txBytes:90  txPkts:1  localName:"nbu1x2"}  disk:{disk: [...]

2021-11-03 16:28 UTC, rvs commented
Sure @Insei -- but that still doesn't explain why we need a newer kernel ;-)

I mean -- it is fine for the WIP PR -- but if you plan to merge it -- we'll need to know all the gory details of why and what will be changing.

2021-11-04 14:29 UTC, Insei commented
@rvs sure, this PR only for testing.

2021-12-25 12:30 UTC, Insei commented
@rvs

As a result of testing, updating the kernel to 5.10.67 helps to eliminate the error -Synchronous exception at 0x000000005EAED180 on the RPi4 with hypervizor kvm.

Previously, the error occurred when starting, restarting, and shutting down EVE App instances with a 5% chance. those. almost 95% of workflow tests crashed with this error.

With the update of the kernel, 8 workflow tests were carried out and the error is no longer observed.
4 test result i can show with GH Actions, and 4 - i run local tests on my machine.
https://github.com/Insei/eve/actions/runs/1616508683 (4 attemts all fail on the eve update test)

Do we have the option to update the kernel version? Or are we going to switch to the new release 5.15.x of LTS a little later?

2021-12-29 01:49 UTC, rvs approved these changes
LGTM. Fair enough @Insei -- lets bump the minor version -- doesn't look like that big of a deal

2021-12-30 08:06 UTC, Insei commented
@rvs, can you run the integration tests one more time? The first test failed.

2021-12-31 02:42 UTC, rvs approved these changes
Let's try running tests one more time

2021-12-31 06:24 UTC, merged