enable emulate_tpu to support scsi unmap
lf-edge/eve pull request #2389
Opened 2021-11-19 19:21 UTC by giggsoff

In order to support SCSI UNMAP we must enable emulate_tpu for target

2021-11-21 18:45 UTC, rvs requested changes
Before we can merge this @giggsoff can you please update the description with the information around what feature/usecase this is needed for?

2021-11-22 18:55 UTC, zededa-yuri commented
Could you please add something like this in the commit message

```
vhost: enable emulate_tpu to support scsi unmap

By enable option `emulate_tpu` in vhost iblock settings we activating
support scsi `unmap` command, which is an equivalent of trim/discard.

This command allows user to tell the block device that it does not
care about the context of a certain block, and hardware can adjust its
algorithms accordingly.

In our case this should tell ZFS that there is no need to
copy-on-write this block anymore and it can be used for something else.
```

Otherwise LGTM

2021-11-23 10:08 UTC, giggsoff commented
Updated commit message, thanks for suggestion

2021-11-23 10:10 UTC, zededa-yuri approved these changes

2021-11-23 11:45 UTC, rvs approved these changes
LGTM

2021-11-23 11:46 UTC, merged