sort disks in mount_disk.sh
lf-edge/eve pull request #2436
Opened 2021-12-20 13:00 UTC by giggsoff

Seems we must sort output of find command to be in the same order as items in the mountPoints file.

2021-12-20 18:12 UTC, eriknordmark requested changes
Not sure I understand the issue.
Is this just to handle the case when we have a mount on /a/b and an separate mount on /a/b/c and we need those to be done in that order?

You are sorting on the name of the block device which has nothing to do with the target hence I'm clearly missing something. Can you update the description with what failed?

2021-12-20 22:12 UTC, eriknordmark approved these changes
LGTM

2021-12-22 22:10 UTC, giggsoff commented
Assume test failing on networks overlap die to no retrial mechanism, we delete network in the previous test (with the same subnet), but current test still fail after enough long waiting.

2021-12-23 05:59 UTC, rvs requested changes
Hey @giggsoff -- I am still confused as to why this is needed. Can you please explain in more details?

2021-12-23 10:35 UTC, giggsoff commented
> Hey @giggsoff -- I am still confused as to why this is needed. Can you please explain in more details?

Let me explain in more details:

1. We have the app with two additional volumes: 
```
6a288b90-2246-40b6-b43d-dcb20f9e841c -> /tst1
9b249858-4234-4ba7-821b-8acc70a6dd3b - > /tst2
```
2. In qemu configuration I can see correct order (first volume have less pci address):
```
[drive "drive-virtio-disk0"]
  file = "/persist/vault/volumes/6a288b90-2246-40b6-b43d-dcb20f9e841c#0.qcow2"
...
[device "virtio-disk0"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.4"
...
[drive "drive-virtio-disk1"]
  file = "/persist/vault/volumes/9b249858-4234-4ba7-821b-8acc70a6dd3b#0.qcow2"
... 
[device "virtio-disk1"]
  driver = "virtio-blk-pci"
  scsi = "off"
  bus = "pci.5"
```
3. Inside mountPoints I also can see correct order:
```
b65f239a-64b8-4959-bd76-2e850317bb29:~# cat /persist/vault/volumes/430a729c-8e32-427d-9940-ce2ec45e0042\#0.container/mountPoints 
/tst1
/tst2
```
4. But inside container-in-VM the order is wrong:
```
6aed8661-2643-45d2-a2d2-f2fdac36d420:~# mount|tail -n 2
/dev/vdb on /tst1 type ext2 (rw,relatime)
/dev/vda on /tst2 type ext2 (rw,relatime)
```
5. The reason for that is in wrong output of find we have inside mount_disk.sh (we get line by line from output and from mountPoints file, so we will assign vdb to /tst1, it is wrong):
```
6aed8661-2643-45d2-a2d2-f2fdac36d420:~# find /sys/block/ -maxdepth 1 -regex '.*[sv]d.*' -exec basename '{}' ';'
vdb
vda
```
6. With additional sort proposed in the PR we will have the correct order:
```
6aed8661-2643-45d2-a2d2-f2fdac36d420:~# find /sys/block/ -maxdepth 1 -regex '.*[sv]d.*' -exec basename '{}' ';'|sort
vda
vdb
```

2021-12-24 03:31 UTC, rvs approved these changes
Aha! That makes perfect sense! LGTM

2021-12-26 16:08 UTC, merged