embed cpu microcode updates
lf-edge/eve pull request #2448
Opened 2022-01-04 14:23 UTC by giggsoff

We can see problems running VMs with intel microcode embedded because of no possibility to update it from inside of VM. Seems we should use up-to-date microcode from host-side (EVE), so, I put intel and amd ucode initrd into /boot inside fw package (which expand size by 5MB) and remove rpi and tegra blobs from fw for amd64 (to reduce size by 17MB).
Also I add knobs to grub to use ucode on boot `set_intel_ucode_boot` and `set_amd_ucode_boot` (it may affect booting process in some cases, so, seems, it is better to have it disabled by default).

2022-01-05 07:13 UTC, rvs requested changes
Ok, this is quite a change to EVE boot architecture @giggsoff -- first of all we will need WAY more justification than a simple "We can see problems running VMs with intel microcode embedded because of no possibility to update it from inside of VM."

2022-01-05 12:02 UTC, giggsoff commented
> Ok, this is quite a change to EVE boot architecture @giggsoff -- first of all we will need WAY more justification than a simple "We can see problems running VMs with intel microcode embedded because of no possibility to update it from inside of VM."

I put additional information into description of PR.

2022-01-07 01:48 UTC, rvs requested changes
I still don't understand why those microcode blobs need to come from initrd as opposed from a root fs

2022-01-07 01:48 UTC, rvs commented
> I put additional information into description of PR.

thanks @giggsoff -- that's very helpful. Still, I don't understand why those microcode blobs need to come from initrd as opposed from a root fs

2022-01-07 09:17 UTC, giggsoff commented
> > I put additional information into description of PR.
> 
> thanks @giggsoff -- that's very helpful. Still, I don't understand why those microcode blobs need to come from initrd as opposed from a root fs

They should be integrated as initrd and booted at earlier stages of EVE (it is [recommended](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files#recommendation) and in this case we can control to boot them or not, I select this option) or compiled into kernel of EVE.

2022-01-07 11:06 UTC, eriknordmark commented
> Seems we should use up-to-date microcode from host-side (EVE), so, I put intel and amd ucode initrd into /boot inside of fw package

How does this help for a guest VM (which is where you say there is an issue)? Is it that we need to load in the latest CPU microcode once to make sure that both EVE-OS and guest VMs use that microcode? Or do we also need to do something for the guest VMs?

2022-01-07 11:19 UTC, giggsoff commented
> > Seems we should use up-to-date microcode from host-side (EVE), so, I put intel and amd ucode initrd into /boot inside of fw package
> 
> How does this help for a guest VM (which is where you say there is an issue)? Is it that we need to load in the latest CPU microcode once to make sure that both EVE-OS and guest VMs use that microcode? Or do we also need to do something for the guest VMs?

In case of updated microcode load in CPU by kernel of EVE-OS, its (microcode) version also visible by guest kernel. And guest will not try to update microcode during kernel boot. So, it is nothing to do from inside of VM.

2022-01-24 10:17 UTC, rvs commented
> CONFIG_EXTRA_FIRMWARE

Can you please send a draft PR @giggsoff ?

2022-01-26 20:30 UTC, giggsoff commented
> > CONFIG_EXTRA_FIRMWARE
> 
> Can you please send a draft PR @giggsoff ?

It will be something like that https://github.com/itmo-eve/eve/commit/516b60f4ffd616ac3030bb5ae2cfafceef439860

2022-01-27 11:37 UTC, rvs commented
This seems preferred -- but I'd rather statically check firmware blobs into pkg/kernel

2022-01-27 13:54 UTC, giggsoff commented
> 

Do you mean to download and store blobs in a folder inside pkg/kernel?

2022-01-27 14:05 UTC, rvs commented
Yup. But please add a blurb into the pkg/kernel/README as to where they came from

2022-01-28 14:19 UTC, giggsoff commented
New version is in #2482

2022-01-28 14:19 UTC, closed without merging