fix make-raw to properly handle stdin and to not adjust partitions for usbconf
lf-edge/eve pull request #2454
Opened 2022-01-07 18:37 UTC by giggsoff

`tools/makeusbconf.sh -d -i -f ./usb.json -s 8000 usb.img` do not works as expected with defined `usb.json` and stops with empty filesystem and error `/parts/*: No such file or directory`. 
It comes from lines where we check for `/parts` and if it not exists, we extract file comes from tar in stdin. But `/parts` exists, we create it in Dockerfile. So, I add check for tty connected to stdin, if not, we assume that it is pipe from tar.
Another problem I can see is that in case of makeusbconf we create only one partition (from function do_usb_conf) and seems our logic for protective mbr is not applicable there.

2022-01-11 05:28 UTC, rvs requested changes
I am actually really not sure about deciding this based one whether this is called with a tty attached or not. Typically this is not what one wants to do -- I'd like to dig deeper into the underlying cause first

2022-01-11 05:28 UTC, rvs commented on pkg/mkimage-raw-efi/make-raw
> +[ -n "${PROTECTIVE_MBR_LIST}" ] && sgdisk -h"${PROTECTIVE_MBR_LIST}EE" "$IMGFILE"
Shouldn't we address the calling site of where PROTECTIVE_MBR_LIST is set/not set @giggsoff ?

2022-01-11 18:52 UTC, giggsoff commented
> I am actually really not sure about deciding this based one whether this is called with a tty attached or not. Typically this is not what one wants to do -- I'd like to dig deeper into the underlying cause first

As another option we can check for empty/not empty /parts directory to use stdin or not. Also I made explicit check for usb_conf in script to skip hybrid MBR changes.

2022-01-17 16:03 UTC, rvs approved these changes
LGTM

2022-01-17 23:47 UTC, merged