Use custom overlay snapshotter to ensure encryption
lf-edge/eve pull request #2517
Opened 2022-02-17 11:16 UTC by giggsoff

We use `/persist/containerd/io.containerd.snapshotter.v1.overlayfs` for overlay snapshots and this not encrypted. I move them to `/persist/vault/eve.overlay.snapshotter` to use encryption.
Unfortunately it is not possible to make upgrade converter for old snapshots, we should modify containerd meta.db, but it is locked from our init process. So, I use fallback mechanism to try both snapshotters if new one failed.

2022-02-18 12:39 UTC, rvs requested changes
I am confused @giggsoff -- I've always thought we could just configure the snapshotter upfront instead of proxying it. What am I missing?

2022-02-18 14:58 UTC, giggsoff commented
> I am confused @giggsoff -- I've always thought we could just configure the snapshotter upfront instead of proxying it. What am I missing?

Containerd want to use metadata.db file for snapshotter (located in the directory we want to use for snapshots) and seems it is not easy to make this file available for embedded snapshotter during initialisation (we run containerd in init). So I start snapshotter as a routine inside EVE at the time we have encrypted directories available.

2022-02-21 06:52 UTC, deitch commented
I am trying to wrap my head around this at a more basic (architectural) level.

It looks like (based on the code changes) we are using (or at least support) zfs snapshotter now, via proxy plugin. Is that changing? What is the path being used? Do we use overlay now and are simply changing what directory it is using? If so, then why the more complex-looking change?

2022-03-28 16:40 UTC, giggsoff commented
Closing it with https://github.com/lf-edge/eve/pull/2524 opened

2022-03-28 16:40 UTC, closed without merging