Extract raw filename from mime
lf-edge/eve pull request #2557
Opened 2022-03-15 22:35 UTC by eriknordmark

This is necessary to handle new version of the mime package and allow creating the CDROM directory layout for cloud-init.

2022-03-16 09:06 UTC, deitch requested changes
This definitely would solve the issue, by forcing our usage of `filename` down to the pre-go-1.17 non-RFC-compliant format.

Is this something that we want hard-coded in here?

Can we have this as an option to `handleMimeMultipart()`? So it looks like this?

```go
func handleMimeMultipart(dir string, ciStr string, allowFullFilenamePaths bool) (bool, error) {
```

Then the behaviour is:

```go
		var filename string
		if allowFullFilenamePaths {
 	 		// Note that p.FileName() now excludes the directory part of
 	 		// the filename to conform with RFC 7578, but we need that to
 		 	// be able to layout the CDROM image so we extract the
 	 		// field directly. Note that we check that we use filepath.Clean
 	 		// to avoid escapes outside of the dir.
 		 	v := p.Header.Get("Content-Disposition")
 	 		_, dispositionParams, err := mime.ParseMediaType(v)
 	 		if err != nil {
 			 	dispositionParams = make(map[string]string)
 		 	}
 		 	filename = dispositionParams["filename"]
 	 	} else {
 			filename = p.FileName()
 	 	}
```

2022-03-16 13:11 UTC, eriknordmark commented
> Can we have this as an option to `handleMimeMultipart()`? So it looks like this?

I can make it be an option. But I'd really like to figure out how we can avoid this mime multipart handlling in EVE-OS. A cloud-init compatible guest VM should handle it but not all are compatible.

2022-03-16 13:19 UTC, deitch commented
> But I'd really like to figure out how we can avoid this mime multipart handlling in EVE-OS. A cloud-init compatible guest VM should handle it but not all are compatible.

I agree 100%. I think the whole piece should be out of eve-os. Whatever you pass as userdata will be passed to the guest ECO verbatim. If the ECO image cannot handle it, that is its problem, not eve-os's.

> I can make it be an option. 

If we have to have this, then we probably should make it an option. If we can get out of this business entirely, all the better.

2022-03-16 15:25 UTC, milan-zededa approved these changes

2022-03-16 20:43 UTC, merged

2022-04-13 14:00 UTC, rvs reviewed
LGTM