Add autoreplace and autoexpand property for zpool
lf-edge/eve pull request #2596
Opened 2022-04-19 17:15 UTC by vk-en

Add autoreplace and autoexpand property for zpool.

Those settings will help us avoid additional commands being run by humans when performing storage expansion/replacement operations.

2022-04-21 16:36 UTC, eriknordmark reviewed
I'd like to understand this more and have @zedi-pramodh look at it as well.

To date the idea has been to show failed/degraded drives in the UI (and also generate events for that) and also show added unused drives in the UI, and then let the user choose whether to do add/expand or drive replacement.

The thing we need to discuss is whether there will be use cases where folks will ship boxes with spare drives and whether autoreplace or autoexpand would be useful in such a case. 
I haven't looked at the details of how the autoreplace or autoexpand determins what actions to take when so it would be good to walk through that. Maybe we can use the EVE-OS office hours call next Thursday to talk about this?

2022-04-21 16:42 UTC, zedi-pramodh commented
@eriknordmark  the auto expand helps in automatically expansing pool size when the existing disks are replaced with bigger size disks, it basically avoids a non-technician to run an additional command on the system, even if using zedcloud we can avoid an additional step.

auto replace helps replacing a failed disk if there is a spare disk on the device. 

In both cases we can avoid user running an additional command.

Sure let's discuss in Storage meetings next week.

2022-07-06 13:39 UTC, eriknordmark commented
> @eriknordmark the auto expand helps in automatically expansing pool size when the existing disks are replaced with bigger size disks, it basically avoids a non-technician to run an additional command on the system, even if using zedcloud we can avoid an additional step.

I suspect we will end up capturing something about the number of drives and possibly their size in the hardware model for the device so that the user can track the intented hardware configuration(s) across their fleet.
So there will be some steps in the workflow to replace drives.

For auto-replace it seems like we first need to decide whether we are going to introduce some workflow where drives are setup as spares (using the EVE API), so that they can be used automatically. But before we set some options lets first write down and agree on those workflows when it comes to drive additions and replacements.

2022-07-06 13:40 UTC, eriknordmark requested changes
This doesn't make sense at this point in time as said in the comment I just added.Might make sense later.

2023-01-19 11:49 UTC, rouming commented
@eriknordmark could you please close this with the "stalled" label?

2023-01-25 23:43 UTC, eriknordmark commented
Closing as stalled

2023-01-25 23:43 UTC, closed without merging