Add TPM support for UEFI and make it easier to build DEBUG target
lf-edge/eve pull request #2697
Opened 2022-07-01 17:51 UTC by mikem-zed

Signed-off-by: Mikhail Malyshev <mikem@zededa.com>

2022-07-06 13:02 UTC, eriknordmark reviewed
I assume this builds on top of #2624. Is that correct?
@mikem-zed any answer?

2022-07-11 12:57 UTC, eriknordmark approved these changes
LGTM

2022-07-28 15:13 UTC, eriknordmark approved these changes
Run eden again

2022-11-09 10:27 UTC, rouming commented
@eriknordmark @mikem-zed 
I assume this is still valid. Can we merge this?

2022-11-19 02:13 UTC, eriknordmark requested changes
@mikem-zed this has a confict which needs to be resolved

2022-11-19 21:35 UTC, mikem-zed commented on pkg/uefi/build.sh
> +     x86_64) build -b ${TARGET} -t GCC5 -a X64 -p OvmfPkg/OvmfPkgX64.dsc -D TPM_ENABLE=TRUE -D TPM_CONFIG_ENABLE=TRUE
there is no such support unfortunately

2022-11-22 05:16 UTC, eriknordmark approved these changes
LGTM

2022-11-22 23:24 UTC, merged