Fix typos and small errors throughout the documentation
lf-edge/eve pull request #2698
Opened 2022-07-04 12:30 UTC by rene

This commit fixes some typos and small errors throughout documentation files
under docs/.

Signed-off-by: Renê de Souza Pinto <rene@renesp.com.br>

2022-07-04 17:16 UTC, eriknordmark requested changes
Seems like yetus found a spelling error in your fixes.

2022-07-05 10:06 UTC, zededa-yuri approved these changes

2022-07-05 12:47 UTC, rene commented
Updates in this PR:
- Fix one typo found by Yetus.

2022-07-05 13:36 UTC, eriknordmark approved these changes
LGTM

2022-07-05 13:37 UTC, merged