Add wireguard module to kernel
lf-edge/eve pull request #2702
Opened 2022-07-06 12:27 UTC by eriknordmark

This enables OCI contrainers running on EVE-OS to use wireguard.
Those are run using the same kernel as we have in the host.
At some point in time maybe we want a separate kernel for the host and the container runtime.

2022-07-06 17:21 UTC, deitch approved these changes
LGTM, although CI is not happy.

2022-07-07 07:04 UTC, giggsoff requested changes
Please adjust riscv64 kernel config: [0001-Fix-riscv64-kernel-config.txt](https://github.com/lf-edge/eve/files/9061185/0001-Fix-riscv64-kernel-config.txt)

2022-07-15 08:36 UTC, milan-zededa approved these changes

2022-08-01 12:08 UTC, zededa-yuri reviewed
Would you mind adding the

2022-08-01 12:08 UTC, zededa-yuri commented on pkg/kernel/kernel_config-5.10.x-x86_64
> -# CONFIG_WIREGUARD is not set
Out of curiosity. You just did 'make menuconfig' and enabled `CONFIG_WIREGUARD`. And all the other changes are done by linux's configuration utility? Or there is more to that.

The reason I ask, is that I had an urge to introduce config fragments for a little while. Which is a bit hard to do at the moment without knowing the intention of changes which have been done to `.config` in the past.

2022-09-07 20:38 UTC, zedi-pramodh approved these changes
LGTM.

2022-11-09 10:50 UTC, rouming commented
This seems to me partially copies #2711 . Still the same question: why do we need to load modules from the xen-tools container and not from a rootfs from a single place? It is already quite difficult to figure out the correct booting sequence and module order, and if containers start load modules (which are asynchronous to each other) - this gets really complicated and messy.

2023-04-12 23:28 UTC, zedi-pramodh approved these changes
LGTM

2023-04-18 00:21 UTC, merged