README.md: add Mac M1 helps and clarifications
lf-edge/eve pull request #2837
Opened 2022-09-29 04:09 UTC by famleebob

Added dependencies not mentioned in the instructioins to install `qemu`.

Added Mac M1 specific steps required to cross build.  Working from this README, could not complete the cross build.  Eric recalled the `redit` article, which allowed completion of the cross build (that is, `amd64` build on the `aarch64` Mac M1.

Signed-off-by: Gerald (Bob) Lee <bob@famleehouse.net>

2022-09-29 15:20 UTC, deitch commented
Thanks for squashing it. You need to sign DCO.

I don't get why we need to run binfmt. I am pretty sure docker desktop (which runs on macOS) includes binfmt already. I can double-check.

2022-09-29 15:23 UTC, deitch commented
Yeah, just ran a test, and I definitely have binfmt running on my macOS, by default as far as I know.

That won't be true for OSS dockerd run on linux, because it is the Docker Desktop (closed source) that includes it. But Docker Desktop (Mac and Windows) includes it. 

Without running the binfmt container, did you try the tests listed [here](https://github.com/tonistiigi/binfmt#test-current-emulation-support)?

2022-09-30 05:11 UTC, famleebob commented
I executed the `docker run` commands in the README:

```
gerald@Administrators-MacBook-Pro bob_stuff % docker run --rm arm64v8/alpine uname -a
Unable to find image 'arm64v8/alpine:latest' locally
latest: Pulling from arm64v8/alpine
9b18e9b68314: Already exists 
Digest: sha256:ed73e2bee79b3428995b16fce4221fc715a849152f364929cdccdc83db5f3d5c
Status: Downloaded newer image for arm64v8/alpine:latest
Linux 717196910a73 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 Linux
gerald@Administrators-MacBook-Pro bob_stuff % docker run --rm arm32v7/alpine uname -a
Unable to find image 'arm32v7/alpine:latest' locally
latest: Pulling from arm32v7/alpine
c6556b3b6858: Pull complete 
Digest: sha256:0c673ee68853a04014c0c623ba5ee21ee700e1d71f7ac1160ddb2e31c6fdbb18
Status: Downloaded newer image for arm32v7/alpine:latest
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Linux 41f6014cb2c8 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 armv7l Linux
gerald@Administrators-MacBook-Pro bob_stuff % docker run --rm ppc64le/alpine uname -a
Unable to find image 'ppc64le/alpine:latest' locally
latest: Pulling from ppc64le/alpine
c79e5d1a8c89: Pull complete 
Digest: sha256:fa30af02cc8c339dd7ffecb0703cd4a3db175e56875c413464c5ba46821253a8
Status: Downloaded newer image for ppc64le/alpine:latest
WARNING: The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Linux 4ced2bc1bade 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 ppc64le Linux
gerald@Administrators-MacBook-Pro bob_stuff % docker run --rm s390x/alpine uname -a
Unable to find image 's390x/alpine:latest' locally
latest: Pulling from s390x/alpine
790c84f1f340: Pull complete 
Digest: sha256:c2046a6c3d2db4f75bfb8062607cc8ff47896f2d683b7f18fe6b6cf368af3c60
Status: Downloaded newer image for s390x/alpine:latest
WARNING: The requested image's platform (linux/s390x) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Linux 2cf6cda1b4b1 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 s390x Linux
gerald@Administrators-MacBook-Pro bob_stuff % docker run --rm tonistiigi/debian:rescv uname -a
Unable to find image 'tonistiigi/debian:rescv' locally
docker: Error response from daemon: manifest for tonistiigi/debian:rescv not found: manifest unknown: manifest unknown.
See 'docker run --help'.
gerald@Administrators-MacBook-Pro bob_stuff % docker run --rm tonistiigi/debian:riscv uname -a
Unable to find image 'tonistiigi/debian:riscv' locally
riscv: Pulling from tonistiigi/debian
ab1025fa84a4: Pull complete 
Digest: sha256:20feb43a774fa82173f037b53736b70b193686c6a63897f23ccbc6d83deb7d48
Status: Downloaded newer image for tonistiigi/debian:riscv
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Linux b1e18cfb9fd0 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 riscv64 GNU/Linux
```

I managed to install docker on my M1 Mac, and the cross-build failed.  I've messed with it enough that getting back to the original condition is more than I'd like to do right now.

As this failure is more common on `linux` how about I change the short description to:

`Should the cross build fail`

Sound more accurate?

2022-09-30 08:01 UTC, deitch commented
All that having been said, marking it as, "if this doesn't work, you may need to install binfmt support is a good approach. I wouldn't make it part of M1 Macs, though. I would just do it in general.

But we already have it. [These lines](https://github.com/lf-edge/eve/pull/2837/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L82-L86) do the same thing, install binfmt support. So perhaps we should change the lines from:

<pre>
##### Enable execution of different multi-architecture containers
This step is required on **Linux** and is required to create eve bootable images with a different architecture than the host architecture.
```sh
 $ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
 ```
</pre>

To:

<pre>
##### Enable execution of different multi-architecture containers

[binfmt](http://binfmt-support.nongnu.org) is required to create eve bootable images with a different architecture than the host architecture. it is enabled by default when running Docker Desktop for any platform: Windows, macOS (x86 and M1) and Linux.

If you are running docker engine without Docker Desktop, or have issues running alternate architectures, then you can enable it by:

```sh
 $ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
 ```
</pre>

2022-09-30 08:02 UTC, deitch commented
And you still need to sign the DCO :-)

2022-10-03 23:36 UTC, eriknordmark approved these changes
LGTM but I don't run on a Mac.
@deitch does it make what you've seen?

2022-10-04 08:20 UTC, deitch commented
I have had no issues at all with the build, so I have not needed these steps. But they are written as a fallback, "should it fail" and "you may also need these", and those are reasonable. So fine with me.

2022-10-07 22:41 UTC, eriknordmark requested changes
Seems like the additions use xml syntax and not markdown syntax which makes yetus complain. Can you fix that and we can merge this?

2022-10-10 16:53 UTC, famleebob commented
Quoting Erik Nordmark ***@***.***>:

> @eriknordmark requested changes on this pull request.

> Seems like the additions use xml syntax and not markdown syntax  
> which makes yetus complain. Can you fix that and we can merge this?

Will do, was going to ask about this.

> --
> Reply to this email directly or view it on GitHub:
> https://github.com/lf-edge/eve/pull/2837#pullrequestreview-1135124372
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

-bob

2022-10-11 00:29 UTC, eriknordmark approved these changes
LGTM

2022-10-11 00:30 UTC, merged