pillar: build delve using install command
lf-edge/eve pull request #2850
Opened 2022-10-07 14:13 UTC by yvolchkov

`go get` is depricated. Switch to `go install`

Signed-off-by: Yuri Volchkov <yuri@volch.org>

2022-10-07 22:48 UTC, eriknordmark requested changes
Seems like there are three changes here:
1. up the version on dlv
2. pass in empty GOFLAGS (where yetus complains about the syntax for some reason)\
3. changing go get to go install

#1 is fine.
I don't understand the reason for #2.
#3 doesn't match what I see in e.g., https://stackoverflow.com/questions/24878737/what-is-the-difference-between-go-get-and-go-install where it seems to recommend to do go get -d followed by a go install to be future proof. Clearly just a go install will not suffice.

Can you clean this up and also have the title and description reflect the nature and motivation of the changes.

2022-10-10 10:34 UTC, yvolchkov commented
both 3 and 2 always has been problems, which are surfaced with the recent update of linuxkit/go

If you build without any changes with DEV=y now, you first will run into #3:
```
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

Simple change of `get` to `install` will reveal the problem #2

```
go: github.com/go-delve/delve/cmd/dlv@v1.8.3: cannot query module due to -mod=vendor
```

Sorry I should have added all of this in the commit. Will do

2022-10-10 15:17 UTC, yvolchkov commented
In the newer version I replaced 'GOFLAGS=' with 'unset GOFLAGS'. Hopefully it will be less confusing for yetus

2022-10-11 17:19 UTC, eriknordmark approved these changes
LGTM

2022-10-12 01:02 UTC, eriknordmark commented
@yvolchkov the arm build is failing as shown in https://github.com/lf-edge/eve/actions/runs/3220427924/jobs/5285773787

2022-10-12 16:51 UTC, yvolchkov commented
> @yvolchkov the arm build is failing as shown in https://github.com/lf-edge/eve/actions/runs/3220427924/jobs/5285773787

Could it be flakiness of GitHub action? The `make ZARCH=arm64 eve` worked on my computer

2022-10-12 17:46 UTC, giggsoff commented
> > @yvolchkov the arm build is failing as shown in https://github.com/lf-edge/eve/actions/runs/3220427924/jobs/5285773787
> 
> Could it be flakiness of GitHub action? The `make ZARCH=arm64 eve` worked on my computer

Looks like not related problem, correct. We failed to get cache https://github.com/lf-edge/eve/actions/runs/3220427924/jobs/5285773787#step:3:6 but it was ok here https://github.com/lf-edge/eve/actions/runs/3220427924/jobs/5285773679#step:3:17 for the same cache key.
What confuse me, I can see the difference between actions runs was more than a day (it was attempt 2). So potentially cache may be removed between attempts (as cache is limited and may be removed by GH, please correct me if I am wrong @deitch). So seems we should avoid retrying only failed jobs here and retry the whole workflow.

2022-10-13 09:03 UTC, deitch commented
You are correct. There are two jobs in this workflow:

1. `packages`
2. `eve`

`packages` builds once on each architecture, while `eve` builds once for each target (matrix of architecture and hypervisor). The output of `packages` is cached using GitHub Actions cache, and then loaded into `eve`.

GHA caches have a maximum size with FIFO. As more caches get used, the oldest one is removed. That means that if we wait long enough from running `packages` until we run `eve`, the cached packages are timed out, `eve` gets a cache miss, and the job fails.

Normally this does not happen, since `eve` jobs get run immediately after `packages`. But since we can rerun just one job a day or two later, we can trigger this. Which is what happened here.

I am opening a PR for the `eve` job so that it not only tries to load from the cache, but also checks for a cache miss, and, if a miss occurs, immediately stops with an error message saying you need to rerun all of the jobs.

See #2856

2022-10-14 22:48 UTC, merged