[DRAFT] Add virtual eve deployment doc draft
lf-edge/eve pull request #2851
Opened 2022-10-09 00:43 UTC by bayupw

This PR adds a document about important notes and instructions on how to deploy virtual eve for testing purposes especially in a scenario when hardware is not available.

Some images to describe the overall high level workflow if required
[](https://raw.githubusercontent.com/bayupw/eve/virtual-eve-deployment-images/docs/pics/deploying-in-virtualbox-and-vmware.png)
[](https://raw.githubusercontent.com/bayupw/eve/virtual-eve-deployment-images/docs/pics/deploying-in-gcp.png)

2022-10-09 08:01 UTC, deitch commented
I _do_ like this! It just needs links from the `DEPLOYMENT.md` doc.

2022-10-09 08:20 UTC, bayupw commented
I've missed the VBoxManage script to enable nested-hw-virt
`VBoxManage modifyvm eve-vm1 --cpus 1 --memory 1024 --nic1 nat --hwvirtex on --vtxvpid on --vtxux on --firmware efi --nested-hw-virt on`
Will combine update with other feedback for this doc

2022-10-10 13:44 UTC, rene commented on docs/VIRTUAL-EVE-DEPLOYMENT.md
> +VBoxManage storageattach [vm-name] --storagectl "IDE Controller" --port 0 --device 0 --type hdd --medium "[path]\[disk-name].vdi"
It's better to use a SATA emulated controller here, SATA emulation has a better performance than IDE emulation on Virtualbox...

2022-10-11 19:35 UTC, bayupw commented on docs/VIRTUAL-EVE-DEPLOYMENT.md
> +Prerequisites for deploying EVE-OS in a virtual machine are as follows:
updated

2022-10-12 03:19 UTC, bayupw commented
@eriknordmark let me know if that looks better, thank you!

2022-10-12 04:33 UTC, eriknordmark approved these changes
Looks like a very good start. Let's see if yetus finds any issues.

2022-10-13 10:20 UTC, rene commented
> Looks like a very good start. Let's see if yetus finds any issues.

I agree, looks like a good start. @bayupw , there are some Yetus errors that must be fixed. Also, please, squash your commits, we shouldn't have specific commits related to changes in the PR, made during the review to address reviewer comments. In the case of this PR, you can provide the new documentation file in only one single commit (the first one).

2022-10-14 19:35 UTC, bayupw commented
> > Looks like a very good start. Let's see if yetus finds any issues.
> 
> I agree, looks like a good start. @bayupw , there are some Yetus errors that must be fixed. Also, please, squash your commits, we shouldn't have specific commits related to changes in the PR, made during the review to address reviewer comments. In the case of this PR, you can provide the new documentation file in only one single commit (the first one).

Thanks @rene I'll take a look at the Yetus error and will resolve them. Will fix the commits as well

2022-10-17 22:43 UTC, eriknordmark requested changes
LGTM but two things to fix
1. There are a number of yetus (markdownlint, spaces) issues to fix which appear as annotations in https://github.com/lf-edge/eve/pull/2851/files
2. Once that is done, please squash the 3 commits into a single commit.

Thanks!

2023-04-24 19:10 UTC, closed without merging