update readme to reflect rule in makefile
lf-edge/eve pull request #3029
Opened 2023-02-08 17:47 UTC by mikero8

The README.md doesn't contain right rule to make eve-edgeview container image, so update the README to reflect latest rule from Makefile

Signed-off-by: Mike Pu [puzhwei@gmail.com](mailto:puzhwei@gmail.com)

2023-02-08 18:03 UTC, naiming-zededa approved these changes
LGTM

2023-02-08 21:05 UTC, eriknordmark approved these changes
LGTM

2023-02-08 21:11 UTC, eriknordmark requested changes
I see the DCO check failed. Can you follow the instructions in
https://github.com/lf-edge/eve/pull/3029/checks?check_run_id=11203484606
and update the PR?

2023-02-08 22:16 UTC, mikero8 commented
> I see the DCO check failed. Can you follow the instructions in https://github.com/lf-edge/eve/pull/3029/checks?check_run_id=11203484606 and update the PR?

Thank you! I followed the instructions and updated the PR

2023-02-09 01:13 UTC, eriknordmark approved these changes
LGTM

2023-02-09 07:06 UTC, merged