add tool to calculate go equivalent pseudo-version
lf-edge/eve pull request #3102
Opened 2023-03-15 00:15 UTC by deitch

This is not used at all, but captures how to calculate go module version or pseudo-version. We will use it in the future.

2023-03-17 14:12 UTC, eriknordmark approved these changes
Run checks

2023-03-21 18:38 UTC, eriknordmark requested changes
Seems like those yetus complaints should be addressed.
Also, can you add a Copyright and SPDX-License line to the top of the file?

2023-03-22 09:03 UTC, deitch commented
Copyright line and SPDX-License line added. Also addressed yetus.

2023-03-22 10:03 UTC, deitch commented
Ah, _now_ yetus is happy.

2023-03-22 10:48 UTC, eriknordmark approved these changes
LGTM

2023-03-22 12:30 UTC, merged