new-kernel:fix cross build
lf-edge/eve pull request #3132
Opened 2023-03-31 04:41 UTC by famleebob

`EVE_TARGET_ARCH` must be correctly and consistenly set to correclty build expected targets.  Further, `EVE_BUILD_ARCH` must be set to reflect the curren build host architecture.  The correct value for this is provided by `buildkit` as `BUILDARCH`, only used in one place.

Validated by building `arm64` on `arm64`, `amd64` on `arm64`, and `riscv64` on `arm64`.

Need to have this change validated with `arm64` on `amd64, and `amd64` on `amd64`, and `riscv64` on `amd64`.

2023-04-24 15:50 UTC, rene commented on pkg/new-kernel/Dockerfile
> -        --host="${EVE_TARGET_ARCH}"-linux-musl --build="${EVE_BUILD_ARCH}"-linux-musl && \
@famleebob , did you figure out why EVE_BUILD_ARCH is not reflecting the right architecture here? In theory you shouldn't need to change this variable....

2023-04-25 11:45 UTC, rene commented
> @famleebob , I will test on my x86 host and post results here...

I've performed the following builds (all successfully):

| host | target |
|-------|------|
| x86 | x86 |
| x86 | aarch64 |
| x86 | riscv64 |

@famleebob , note, however, that you will need to rebase your PR....

2023-04-28 00:15 UTC, famleebob commented
repeated the three builds on my Mac M1, after the last rebase.

2023-04-28 19:12 UTC, eriknordmark commented
@famleebob you need a DCO signature on each commit. See instructions.

2023-05-01 20:23 UTC, famleebob commented
The problem with the DCO check was the email address I used.  Corrected that with a commit. Looks like all is ready to go.

2023-05-02 00:24 UTC, eriknordmark approved these changes
Run eden again

2023-05-02 11:25 UTC, rene approved these changes
LGTM.

2023-05-02 14:22 UTC, rene requested changes

2023-05-02 14:22 UTC, rene commented on pkg/new-kernel/Dockerfile
> +ARG BUILDARCH
@famleebob, you forgot this ARG from the first version of the PR, we don't need it anymore (correctly pointed out by @christoph-zededa)

2023-05-03 09:02 UTC, famleebob commented
Updated per comments (thanks Christoph).

2023-05-03 09:09 UTC, famleebob commented
Re-ran builds on all three architectures (`amd64`, `aarch64`, and `riscv64`)

2023-05-08 10:59 UTC, rene commented
@famleebob , just a final touch, since you already ran the tests, you can remove the following excerpt from your commit message:
```
Validated by building `arm64` on `arm64`, `amd64` on `arm64`, and
`riscv64` on `arm64`.

Need to have this change validated with `arm64` on `amd64`, and
`amd64` on `amd64`, and `riscv64` on `amd64`.
```
maybe just let a sample phrase telling the changes were validated for all (arm64, amd64 and riscv64)...

2023-05-12 01:33 UTC, famleebob commented
Tested build on x86_64 machine for (amd64, arm64, and riscv64) native/cross builds.

2023-05-12 12:41 UTC, eriknordmark commented
@famleebob seems like you have 29 more commits than you should in this PR. Please rebase on master and then make sure you have a single commit for your changes (and no merge commits).
FWIW I setup my workspaces with git remote add upstream https://github.com/lf-edge/eve, and then I can do git fetch upstream master; git rebase -i upstream/master.
That way I can ensure I don't get any merge commits.

2023-05-15 08:21 UTC, merged