[8.12 stable] Move HTTP send operations away from the main event loop
lf-edge/eve pull request #3167
Opened 2023-04-26 12:37 UTC by rouming

Zedagent main event loop is responsible for handling pubsub updates along with sending messages to the controller. HTTP send is synchronous call and can stall the whole main event loop for up to 6 minutes (overall send timeout). This badly affects the system responsiveness which can be observed in air gaped environment (no connectivity to the controller), when the queue is stuck waiting for send to be completed and no other pubsub updates are handled. 

Two things are done in this PR:
1. Introduced ```connect()``` ("dial" in terms of Go) timeout, which is less than actual ```send()``` timeout (helps to fail faster).
2. All direct HTTP ```send()``` calls are moved away from the main event loop and executed in dedicated goroutines.

This is the backport of original patches from @milan-zededa to the 8.12 stable branch.

CC: @milan-zededa

2023-04-27 13:59 UTC, milan-zededa approved these changes

2023-04-28 19:21 UTC, eriknordmark requested changes
I suspect DCO is failing since you use a different name for the sigonoff.

2023-05-07 17:38 UTC, eriknordmark commented
@rouming this has DCO failure which need to be taken care of. Then we can merge it.

2023-05-08 10:16 UTC, rouming commented
Difference to the previous version:
* DCO fix

2023-05-08 10:17 UTC, rouming commented
Indeed fixed, wow, but the complains was about Ruslan's commit. Thanks Erik for pointing me typo out.

2023-05-08 16:04 UTC, eriknordmark approved these changes
LGTM. Let's run eden.

I'm also running ztests with a tweak to not rely on the inline send just to make sure the timer/trigger logic is solid.

2023-05-09 14:20 UTC, merged