compare sbom and collected_sources manifest
lf-edge/eve pull request #3191
Opened 2023-05-04 14:39 UTC by yash-zededa

- This will install the compare-sbom-sources utility
- Will compare the output of the sbom and the collected_sources target

2023-05-04 14:43 UTC, deitch requested changes
Can you also add it to the `assets.yml` pipeline, so the results are shown there when run?

2023-05-04 14:55 UTC, deitch approved these changes

2023-05-05 12:14 UTC, rene commented
@yash-zededa , it looks like you have squashed some commits during development that have concatenated a lot of "minor fixes" in your commit message. Please, correct them. Let just a summary of the changes you are doing and just one Signed-off in your final commit.

2023-05-05 12:28 UTC, yash-zededa commented
@rene thanks for pointing out. This is fixed.

2023-05-05 17:31 UTC, eriknordmark reviewed
@deitch I see an 		os.Exit(1)
in compare-sbom-sources, but I can't tell wheher that happens when the comparison fails or only for more serious errors.

Also, the command function has log.Fatal which seems odd; shouldn't it return the error to the caller and have the caller fatal/exit?

2023-05-07 11:31 UTC, deitch commented on Makefile
> +	$(COMPARESOURCES) $(COLLECTED_SOURCES):collected_sources_manifest.csv $(SBOM)
Unless the compare fails fully, then, yes, it would exit 0. If the compare has an error, it exits with 1.

2023-05-07 11:32 UTC, deitch commented
@eriknordmark the `os.Exit(1)` is correct; if it cannot execute the command, exit 1.

The `log.Fatal`, on the other hand, shouldn't be there. I will open a PR for it.

2023-05-07 11:34 UTC, deitch commented
See #3195

2023-05-07 17:35 UTC, eriknordmark approved these changes
LGTM

2023-05-07 17:35 UTC, merged