make eve version from file rather than templating
lf-edge/eve pull request #3255
Opened 2023-05-31 17:15 UTC by deitch

as discussed with @eriknordmark in #3251 , this uses a similar approach, removing templating for the `EVE_VERSION` from `rootfs.yml.in` and just reusing a file in `installer/` that already exists.

It requires some changes to `makerootfs.sh` so that it knows what directory to run.

2023-05-31 21:33 UTC, eriknordmark requested changes
Conflict to resolve before yetus can run.

2023-06-01 07:20 UTC, deitch commented
Resolved the conflict

2023-06-01 07:49 UTC, deitch commented
yetus found some issues, think I addressed. Let it run and see.

2023-06-01 08:41 UTC, deitch commented
yetus likes me now!!

2023-06-01 13:37 UTC, eriknordmark approved these changes
LGTM; let it run tests

2023-06-05 17:05 UTC, merged