The version of verification for iPXE.
lf-edge/eve pull request #3278
Opened 2023-06-12 09:32 UTC by jsfakian

It builds a tarball of artifacts to be used for PXE verification

2023-06-14 09:42 UTC, rene reviewed
@jsfakian , your commit title is too long, it can mess a bit the output of commands like `git log --oneline`. Please, break the information into a short title + commit message (explaining the changes).

2023-06-14 09:42 UTC, rene commented on tools/makenet.sh
> +IMG="$3"
You have introduced a third argument which is mandatory. However, there is no information about it in the help message (line 9) and the checks on line 8 still considers only 2 arguments. Actually I think you could change the order, like this:

`Usage: <input dir> <image file name> <output tar image file>`

So we keep the output tar image file as the last argument, and please, consider use the entire file name as arguemnt, e.g., installer.img, verification.img, etc.

2023-06-14 09:42 UTC, rene commented on Makefile
> +	./tools/makenet.sh $| $@ installer
Let just `installer` or `verification` as argument it's a bit confusing. I would prefer to use the entire name (intaller.img and verification.img).

2023-06-20 12:41 UTC, eriknordmark requested changes
Please address @rene 's comments.

2023-06-22 18:31 UTC, eriknordmark approved these changes
LGTM

2023-06-27 08:21 UTC, merged