Build mkinitfs version 3.8.1 from source
lf-edge/eve pull request #3362
Opened 2023-07-18 11:07 UTC by mikem-zed

Alpine 3.16 has nlplug-findfs tool in mkinitfs package that has very small buffer for uevents and cannot detect file system on some devices with many PCIe devices

Here we build the package from Alpine 3.18 from source

In theory we could create an alpine APK builder container and build APK file. But installing APK files is not really possible because networking is disabled for almost all Linuxkit images we build so it won't be able to download dependencies and they must be specified in

2023-07-23 21:15 UTC, eriknordmark requested changes
Some blanks and codespell yetus issues to fix.
The hadolint error you can ignore (hadolint doesn't know about all flags).

2023-07-24 10:11 UTC, mikem-zed commented
> Some blanks and codespell yetus issues to fix. The hadolint error you can ignore (hadolint doesn't know about all flags).

I did not fix them on purpose. I still want to test this on Supermicro but I'm waiting for the device to be available. So I'm moving this to WIP

2023-07-28 19:24 UTC, famleebob commented
Just a gentle reminder, this package is also used by `pkg/xen-tools`.

2023-07-31 11:39 UTC, mikem-zed commented
> Just a gentle reminder, this package is also used by `pkg/xen-tools`.

this is a very good catch! Thanks Bob! But in xen-tools we run it as `RUN mkinitfs -n -F base -i /init-initrd -o /runx-initrd
` and take our own set of files for initrd. `nlplug-findfs` is not even involved, so we can use a 3.16 version for xen-tools

2023-08-07 17:35 UTC, mikem-zed commented
> Some blanks and codespell yetus issues to fix. The hadolint error you can ignore (hadolint doesn't know about all flags).

I've fixed all lint/yetus issues and also riskv64 build. Tested on NUC and QEMU_arrch64

2023-08-07 18:15 UTC, eriknordmark approved these changes
LGTM

2023-08-08 17:34 UTC, merged