bump up ipinfo
lf-edge/eve pull request #3384
Opened 2023-07-28 14:11 UTC by shjala

`ipinfo` changed to use https instead of http.

2023-07-28 14:43 UTC, shjala commented
it is possible to run unit-test again? it pass on my end : 
```
=== RUN   TestWork
    worker_test.go:70: Running test case output
=== RUN   TestWork/output
=== NAME  TestWork
    worker_test.go:70: Running test case output + sleep
=== RUN   TestWork/output_+_sleep
2023/07/28 14:36:16 dummyWorker sleeping for 1 seconds
=== NAME  TestWork
    worker_test.go:70: Running test case output + error
=== RUN   TestWork/output_+_error
=== NAME  TestWork
    worker_test.go:70: Running test case output + sleep + error
=== RUN   TestWork/output_+_sleep_+_error
2023/07/28 14:36:17 dummyWorker sleeping for 1 seconds
--- PASS: TestWork (2.01s)
    --- PASS: TestWork/output (0.00s)
    --- PASS: TestWork/output_+_sleep (1.00s)
    --- PASS: TestWork/output_+_error (0.00s)
    --- PASS: TestWork/output_+_sleep_+_error (1.01s)
=== RUN   TestLength
    worker_test.go:136: Running test case testlength
2023/07/28 14:36:18 Submit1 took 13.708µs
2023/07/28 14:36:18 dummyWorker sleeping for 1 seconds
2023/07/28 14:36:18 Submit2 took 38.001µs
2023/07/28 14:36:19 dummyWorker sleeping for 2 seconds
2023/07/28 14:36:19 Submit3 took 1.004486882s
--- PASS: TestLength (3.01s)
=== RUN   TestInOrder
time="2023-07-28T14:36:22Z" level=trace msg="periodicGC starting" pid=1234 source=test
    workerpool_test.go:81: Running test case testinorder
time="2023-07-28T14:36:22Z" level=trace msg="Creating new worker" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Creating w.processWork at goroutine:\ngithub.com/lf-edge/eve/pkg/pillar/worker.NewWorker()\n\t/home/shah/eve/pkg/pillar/worker/worker.go:116\ngithub.com/lf-edge/eve/pkg/pillar/worker.(*Pool).TrySubmit()\n\t/home/shah/eve/pkg/pillar/worker/workerpool.go:180\ngithub.com/lf-edge/eve/pkg/pillar/worker_test.TestInOrder()\n\t/home/shah/eve/pkg/pillar/worker/workerpool_test.go:84\ntesting.tRunner()\n\t/usr/local/go/src/testing/testing.go:1576\n" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Creating wp.mergeResult at goroutine:\ngithub.com/lf-edge/eve/pkg/pillar/worker.(*Pool).TrySubmit()\n\t/home/shah/eve/pkg/pillar/worker/workerpool.go:189\ngithub.com/lf-edge/eve/pkg/pillar/worker_test.TestInOrder()\n\t/home/shah/eve/pkg/pillar/worker/workerpool_test.go:84\ntesting.tRunner()\n\t/usr/local/go/src/testing/testing.go:1576\n" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="mergeResult starting" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="processWork starting for context *worker_test.dummyContext" pid=1234 source=test
2023/07/28 14:36:22 dummyWorker sleeping for 1 seconds
time="2023-07-28T14:36:22Z" level=trace msg="succeeded Submit for 1" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Creating new worker" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Creating w.processWork at goroutine:\ngithub.com/lf-edge/eve/pkg/pillar/worker.NewWorker()\n\t/home/shah/eve/pkg/pillar/worker/worker.go:116\ngithub.com/lf-edge/eve/pkg/pillar/worker.(*Pool).TrySubmit()\n\t/home/shah/eve/pkg/pillar/worker/workerpool.go:180\ngithub.com/lf-edge/eve/pkg/pillar/worker_test.TestInOrder()\n\t/home/shah/eve/pkg/pillar/worker/workerpool_test.go:91\ntesting.tRunner()\n\t/usr/local/go/src/testing/testing.go:1576\n" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="maxWorkersUsed 2" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Creating wp.mergeResult at goroutine:\ngithub.com/lf-edge/eve/pkg/pillar/worker.(*Pool).TrySubmit()\n\t/home/shah/eve/pkg/pillar/worker/workerpool.go:189\ngithub.com/lf-edge/eve/pkg/pillar/worker_test.TestInOrder()\n\t/home/shah/eve/pkg/pillar/worker/workerpool_test.go:91\ntesting.tRunner()\n\t/usr/local/go/src/testing/testing.go:1576\n" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="mergeResult starting" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="processWork starting for context *worker_test.dummyContext" pid=1234 source=test
2023/07/28 14:36:22 dummyWorker sleeping for 2 seconds
time="2023-07-28T14:36:22Z" level=trace msg="succeeded Submit for 2" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Creating new worker" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Creating w.processWork at goroutine:\ngithub.com/lf-edge/eve/pkg/pillar/worker.NewWorker()\n\t/home/shah/eve/pkg/pillar/worker/worker.go:116\ngithub.com/lf-edge/eve/pkg/pillar/worker.(*Pool).TrySubmit()\n\t/home/shah/eve/pkg/pillar/worker/workerpool.go:180\ngithub.com/lf-edge/eve/pkg/pillar/worker_test.TestInOrder()\n\t/home/shah/eve/pkg/pillar/worker/workerpool_test.go:98\ntesting.tRunner()\n\t/usr/local/go/src/testing/testing.go:1576\n" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="maxWorkersUsed 3" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Creating wp.mergeResult at goroutine:\ngithub.com/lf-edge/eve/pkg/pillar/worker.(*Pool).TrySubmit()\n\t/home/shah/eve/pkg/pillar/worker/workerpool.go:189\ngithub.com/lf-edge/eve/pkg/pillar/worker_test.TestInOrder()\n\t/home/shah/eve/pkg/pillar/worker/workerpool_test.go:98\ntesting.tRunner()\n\t/usr/local/go/src/testing/testing.go:1576\n" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="mergeResult starting" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="processWork starting for context *worker_test.dummyContext" pid=1234 source=test
2023/07/28 14:36:22 dummyWorker sleeping for 3 seconds
time="2023-07-28T14:36:22Z" level=trace msg="succeeded Submit for 3" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=trace msg="Would exceed maxWorkers of 3" pid=1234 source=test
time="2023-07-28T14:36:22Z" level=error msg="Would exceed maxWorkers of 3"
time="2023-07-28T14:36:23Z" level=trace msg="purgeOld(0) have 3" pid=1234 source=test
time="2023-07-28T14:36:23Z" level=trace msg="purgeOld post GC have 3" pid=1234 source=test
2023/07/28 14:36:23 dummyWorker returning (sleep time 1)
time="2023-07-28T14:36:23Z" level=trace msg="mergeResult got {result:{worker:0x40000b2060 kind:test key:testinorder1 error:<nil> errorTime:{wall:0 ext:0 loc:<nil>} output:sleep1 description:{sleepTime:1 generateOutput:sleep1 generateError:false done:true}}}" pid=1234 source=test
2023/07/28 14:36:24 dummyWorker returning (sleep time 2)
time="2023-07-28T14:36:24Z" level=trace msg="mergeResult got {result:{worker:0x40000b2360 kind:test key:testinorder2 error:<nil> errorTime:{wall:0 ext:0 loc:<nil>} output:sleep2 description:{sleepTime:2 generateOutput:sleep2 generateError:false done:true}}}" pid=1234 source=test
time="2023-07-28T14:36:24Z" level=trace msg="purgeOld(0) have 3" pid=1234 source=test
time="2023-07-28T14:36:24Z" level=trace msg="purgeOld GC 1" pid=1234 source=test
time="2023-07-28T14:36:24Z" level=trace msg="purgeOld post GC have 2" pid=1234 source=test
time="2023-07-28T14:36:24Z" level=trace msg="processWork done for context *worker_test.dummyContext" pid=1234 source=test
time="2023-07-28T14:36:24Z" level=trace msg="mergeResult done" pid=1234 source=test
time="2023-07-28T14:36:25Z" level=trace msg="purgeOld(0) have 2" pid=1234 source=test
time="2023-07-28T14:36:25Z" level=trace msg="purgeOld post GC have 2" pid=1234 source=test
2023/07/28 14:36:25 dummyWorker returning (sleep time 3)
time="2023-07-28T14:36:25Z" level=trace msg="mergeResult got {result:{worker:0x40000b26c0 kind:test key:testinorder3 error:<nil> errorTime:{wall:0 ext:0 loc:<nil>} output:sleep3 description:{sleepTime:3 generateOutput:sleep3 generateError:false done:true}}}" pid=1234 source=test
time="2023-07-28T14:36:25Z" level=trace msg="periodicGC done" pid=1234 source=test
time="2023-07-28T14:36:25Z" level=trace msg="processWork done for context *worker_test.dummyContext" pid=1234 source=test
time="2023-07-28T14:36:25Z" level=trace msg="mergeResult done" pid=1234 source=test
time="2023-07-28T14:36:25Z" level=trace msg="processWork done for context *worker_test.dummyContext" pid=1234 source=test
time="20 [...]

2023-07-28 14:47 UTC, shjala commented
seems the empty force-push worked to restart it.

2023-07-28 17:54 UTC, eriknordmark requested changes
This has a large number of unrelated updates to pkg/newlog (related to eve-api and vendor directory in general). 
I think that is being fixed in a different PR; can we remove them from this PR?

2023-07-29 09:21 UTC, shjala commented
@eriknordmark that's the peculiarity of `go mod vendor`, it doesn't accept an argument to which package I want to cache, this is the sequence I executed on `newlog`: 
```
go get -u github.com/eriknordmark/ipinfo
go mod vendor
```

and it updates lots of others too, I think I can do it without the extra stuff, but then I have to edit the `go.mod/sum` and files manually.

2023-07-31 23:16 UTC, eriknordmark commented
This has overlap with #3380 when it comes to the vendor updates and switching from eve/api to eve-api, so it we can't limit its vendor update to just the ipinfo changes it makes sense to wait for that one to be fixed and merged,

2023-08-01 23:32 UTC, eriknordmark approved these changes
Given that #3380 is delayed I'll merge this now.

2023-08-01 23:32 UTC, merged