Update README.md
lf-edge/eve pull request #3545
Opened 2023-10-30 07:31 UTC by mishrasamiksha

Corrected three words typo error

2023-10-30 08:57 UTC, eriknordmark requested changes
Thank you for fixing this.
But you need to use git commit --signoff to add a signoff line to the commit. That is required by LF-Edge policy. See git log what those message look like.

You can add that using e.g., --reedit-message but if you do it manually you need to make sure it matches the email address associated with your github account.

2023-10-30 09:05 UTC, milan-zededa commented on README.md
> +In addition to that, while we plan to build a fully disaggregated system (with even device drivers running in their separate domains) right now we are just getting started and having containers as a
disaggreagation -> disaggregation

one hell of a word :)

2023-10-30 10:32 UTC, rene commented
@mishrasamiksha , thanks for the fix. I'd also recommend to squash these two commits into only one, besides addressing @eriknordmark's comments... changes are simple and in the same file, so no reasons to split into two commits...

2023-10-31 06:16 UTC, mishrasamiksha commented
sure, i'll make a single commit of these

2023-10-31 06:30 UTC, mishrasamiksha commented
can i close this and create a new PR ? with a single commit ?

2023-10-31 07:05 UTC, mishrasamiksha commented
commit 7476e27fade58d14a0bcde589aec22fc19fb49ec (HEAD -> readme_changes)
Author: Samiksha Mishra <38784342+mishrasamiksha@users.noreply.github.com>
Date:   Mon Oct 30 13:01:07 2023 +0530

    Merged 2 commits Update README.md

2023-10-31 07:07 UTC, mishrasamiksha commented
can you please check this now 
I guess this should work

2023-10-31 08:26 UTC, eriknordmark commented
It doesn't look like you updated the PR,
If you squashed the commits (and added the signed line to the commit message), then you need to do a git push -f to update your branch and the PR.

2023-10-31 08:43 UTC, mishrasamiksha commented
oh right
it is fine now. I can see it. 
thanks (from this i learnt to squish, all thanks to you)

2023-10-31 17:25 UTC, yamcodes commented
I'm curious about requiring contributors to manually squash commits when GitHub offers "[Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)" for committing PR's as one unit of work to `main`. The linked GitHub documentation explains the value of this feature:

> You can use squash and merge to create a more streamlined Git history in your repository. Work-in-progress commits are helpful when working on a feature branch, but they aren’t necessarily important to retain in the Git history. If you squash these commits into one commit while merging to the default branch, you can **retain the original changes with a clear Git history**.

Your [CONTRIBUTING.md](https://github.com/lf-edge/eve/blob/master/CONTRIBUTING.md) file requires enthusiastic contributors to handle this on their own behalf. It also states that it welcomes "**any and all types of contributions** that benefit the community at large, not just code contributions" and that it stands for "Community over Code".

Keeping the above in mind, is there a clear advantage to this strict approach over the more relaxed alternative of having Triage roles use 'Squash and merge' directly?

2023-10-31 18:43 UTC, milan-zededa commented
> I'm curious about requiring contributors to manually squash commits when GitHub offers "[Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)" for committing PR's as one unit of work to `main`. The linked GitHub documentation explains the value of this feature:
> 
> > You can use squash and merge to create a more streamlined Git history in your repository. Work-in-progress commits are helpful when working on a feature branch, but they aren’t necessarily important to retain in the Git history. If you squash these commits into one commit while merging to the default branch, you can **retain the original changes with a clear Git history**.
> 
> Your [CONTRIBUTING.md](https://github.com/lf-edge/eve/blob/master/CONTRIBUTING.md) file requires enthusiastic contributors to handle this on their own behalf. It also states that it welcomes "**any and all types of contributions** that benefit the community at large, not just code contributions" and that it stands for "Community over Code".
> 
> Keeping the above in mind, is there a clear advantage to this strict approach over the more relaxed alternative of having Triage roles use 'Squash and merge' directly?

Doing this automatically leads to ugly commit messages IMHO. Making little effort to keep the commit history clean and easily readable helps everyone who contributes and maintains this project, therefore it is as much appreciated as the commit content itself.
New "enthusiastic contributors" also benefit by learning a new useful skill instead of relying on some automation tool, which outside of Github might not be available.

2023-11-01 20:10 UTC, eriknordmark commented
> > Keeping the above in mind, is there a clear advantage to this strict approach over the more relaxed alternative of having Triage roles use 'Squash and merge' directly?

In addition to getting clear commit messages there are plenty of cases where the developer intentionally wants to several commits in a PR when they each commit can be built independently (e.g., add header files, add code, add docs, add tests can be separate commits). It is the developer who is the expert on this and it is hard for the person doing the merge do second-guess whether the intent was to have separate commits or they should be all done as one commit.

2023-11-01 20:12 UTC, eriknordmark commented
You might have missed my first comment about DCO, but this is an LF Edge policy to require this. See 
https://github.com/lf-edge/eve/pull/3545/checks?check_run_id=18215718215
for information on how to add the signoff.

2023-11-06 10:46 UTC, rene commented
@mishrasamiksha , so as @eriknordmark said, now you just need to sign-off your commit, which can be done with the following command:

`git commit --amend -s` 

Also, take the opportunity to edit the commit message, I would recommend something like this:

README.md: Fix some typos

So at the end if you run `git log` in your branch, you should see something like this in your commit:

```
    README.md: Fix some typos
    
    Signed-off-by: <Your name> <your@email>
```

2023-11-11 04:30 UTC, eriknordmark approved these changes
LGTM but the commit needs to be ammended as @rene suggested,

2023-11-22 16:48 UTC, rene commented
I'm closing this PR since its inactivity. Changes here are now handled in https://github.com/lf-edge/eve/pull/3622

2023-11-22 16:48 UTC, closed without merging