grub: Clear eMMC partition table on ThinkEdge SE70
lf-edge/eve pull request #3552
Opened 2023-11-01 13:29 UTC by rene

The Lenovo ThinkEdge SE70 device comes from factory with a bootable image on the eMMC. However, EVE is installed on the NVMe SSD, so we need to clear eMMC's partition table to avoid any boot attempt from it, letting the device boot normally from the NVMe.

Background: An issue was notice on a brand new device trying to boot from eMMC after EVE's installation. The changes in this PR fixed the issue.

2023-11-01 20:03 UTC, eriknordmark requested changes
I think this needs a bold red warning in the docs in the SE70 to point out that the installer will clear the emmc.

Or is there a way to not do this and instead force the device to prefer booting from the other disk?

2023-11-02 09:39 UTC, rene commented
> I think this needs a bold red warning in the docs in the SE70 to point out that the installer will clear the emmc.
> 
> Or is there a way to not do this and instead force the device to prefer booting from the other disk?

Unfortunately there isn't an easy way to control this from our side (the config options provided by NVIDIA's bootloader are minimal for this platform), I will put the information in the docs. My plan for the future is to install EVE on eMMC and let the NVMe only for persist, so both will be used in any case, but it requires more testing with the installer script.

2023-11-02 10:01 UTC, rene commented
Updates in this PR:
- Rebase on top of master
- Add documentation about wiping of eMMC during installation process

2023-11-02 11:01 UTC, rene commented
Updates in this PR:
- Fix yetus error

2023-11-02 18:16 UTC, eriknordmark approved these changes
LGTM

2023-11-02 18:17 UTC, merged