GitHub actions: switch to BuildJet cache for build.yml workflow
lf-edge/eve pull request #3601
Opened 2023-11-18 09:41 UTC by uncleDecart

Recent build failures might be because of the GitHub cache. Switching to BuildJet cache for more stability and since it gives more space and is free it is a good alternative.

2023-11-18 09:59 UTC, uncleDecart commented
Hitting error. [This](https://github.com/actions/setup-node/issues/503#issuecomment-1144571359) suggest to change cache key

2023-11-20 10:04 UTC, milan-zededa approved these changes

2023-11-20 17:13 UTC, uncleDecart commented
So building packages and EVE on same machine solves caching problem, however we hit exec format error [here](https://github.com/lf-edge/eve/actions/runs/6931579591/job/18853755771?pr=3601#step:8:179). Question right now is what are we doing different in GHA compared to locally running make pkgs && make eve on arm host (locally it works like charm)

2023-11-20 18:36 UTC, eriknordmark commented on .github/workflows/build.yml
> +          - os: ubuntu-22.04
How do we know that this unrelated change to the amd64 build doesn't break anything?

2023-11-20 18:38 UTC, eriknordmark commented on .github/workflows/build.yml
> +        uses: buildjet/cache@v3
What's the impact of this on the amd64 build which does not use buildjet?

2023-11-20 18:41 UTC, eriknordmark requested changes
The amd64 builds are now failing with
exec /usr/bin/yq: exec format error

I think we've had that issue in the past; I thought we only run yq for amd64.

2023-11-21 15:21 UTC, uncleDecart commented
Closing in favor of https://github.com/lf-edge/eve/pull/3609

2023-11-21 15:21 UTC, closed without merging