Edgeview backport from EVE PR #3844
lf-edge/eve pull request #3850
Opened 2024-04-10 09:59 UTC by naiming-zededa

back port patch from PR #3844 on edgeview fix into 11.0.5

2024-04-11 08:08 UTC, milan-zededa approved these changes

2024-04-12 21:24 UTC, eriknordmark requested changes
Why backport the kubevirt support? I thought there was an earlier PR which fixed the API/struct difference with pkg/pillar which needed to be backported.

2024-04-12 23:23 UTC, naiming-zededa commented
@eriknordmark, sorry, i typed in title the number wrong, it should be this one: https://github.com/lf-edge/eve/pull/3536

2024-04-13 05:50 UTC, eriknordmark approved these changes
LGTM

2024-04-18 16:17 UTC, merged