bpftrace: add to debug container
lf-edge/eve pull request #4087
Opened 2024-07-12 14:18 UTC by christoph-zededa

add `bpftrace-aotrt` to the debug container

2024-07-15 09:31 UTC, christoph-zededa commented
it tried to copy an empty directory on riscv64; I hope it builds now successfully.

2024-07-15 10:05 UTC, rouming approved these changes

2024-07-15 13:44 UTC, christoph-zededa commented
build failures:
```
Error: error building "lfedge/eve-debug:21943b9096888218a689ada1e1fa9a2fb4a42e79": error building for arch riscv64: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c su builder -c 'cd /musl && abuild checksum && abuild -r'" did not complete successfully: exit code: 1
2024/07/15 10:54:36 error during command execution: error building "lfedge/eve-debug:21943b9096888218a689ada1e1fa9a2fb4a42e79": error building for arch riscv64: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c su builder -c 'cd /musl && abuild checksum && abuild -r'" did not complete successfully: exit code: 1
make: *** [Makefile:1035: eve-debug] Error 1
```
and
```
eve-build-ubuntu docker container is ready to use
Cloning into '/tmp/linuxkit'...
error: 4504 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
make: *** [Makefile:941: /home/ubuntu/actions-runner/_work/eve/eve/build-tools/bin/linuxkit] Error 128
```

IMO both are unrelated to this PR.

2024-07-20 02:29 UTC, eriknordmark requested changes
The riscv mini build still fails. Might want to rebase on master and see if that changes anything.

2024-07-23 12:46 UTC, christoph-zededa commented
Trying something out regarding these build errors ...

2024-07-23 18:26 UTC, eriknordmark commented
That seems to have fixed it. Now need a DCO fix.

2024-07-24 08:56 UTC, rene commented on pkg/debug/Dockerfile
> +RUN find / -name musl-1.2.3-r0.apk
What is the purpose of this find command? Forgot from debug?

2024-07-24 10:38 UTC, rene commented on pkg/debug/Dockerfile
> +RUN find / -name musl-1.2.3-r0.apk
you can use an approach like here: https://github.com/lf-edge/eve/blob/master/pkg/cross-compilers/Dockerfile#L19 to fetch the whole index beforehand... but I'm wondering why we didn't experience this error before...

2024-07-24 10:57 UTC, rene commented on pkg/debug/Dockerfile
> +RUN find / -name musl-1.2.3-r0.apk
you can also try `apk add --no-network ....`

2024-07-24 20:47 UTC, eriknordmark approved these changes
This appears to be building now. Any reason to keep it as a draft?

2024-07-25 06:16 UTC, christoph-zededa commented
> This appears to be building now. Any reason to keep it as a draft?

No, I was just pessimistic ;-)

2024-07-25 15:10 UTC, merged