Increase rootfs size to 350Mb
lf-edge/eve pull request #4329
Opened 2024-10-08 17:46 UTC by rucoder

- We have only ~2Mb left in roofs. It is time to increase its size

2024-10-09 08:16 UTC, rene approved these changes
LGTM

2024-10-09 19:52 UTC, eriknordmark commented on Makefile
> +# That seems to be the direction taken for existing kvm systems where partition size is 512MB but
512 are the new (since release TBD) but all the older use 300. The comments need to reflect this.

2024-10-09 19:54 UTC, eriknordmark commented on Makefile
> +# rootfs size is limited to 350MB. That helps in catching image size increases earlier than at later stage.
Can't do that when 99% of what's deployed has a partition size of 300MB.

How big is the debug container? Can we handle it the same way we handle k3s and longhorn in EVE kubevirt i.e., remove it from the rootfs?

2024-10-09 19:55 UTC, eriknordmark requested changes
Must allow updates of deployed EVE-OS with a partition size of 300MB. So that is the abolute max.

2024-10-11 13:31 UTC, rucoder commented
> Must allow updates of deployed EVE-OS with a partition size of 300MB. So that is the abolute max.

ah, yes. I knew that 250 limit in not that soft for regular EVE. I'll change to 300. @rene so the size of the image is still the issue and eve cannot grow beyond 300Mb in any near futur. I'm afraid VIM is still on my to-remove list :)

2024-10-11 13:35 UTC, christoph-zededa commented
> > Must allow updates of deployed EVE-OS with a partition size of 300MB. So that is the abolute max.
> 
> ah, yes. I knew that 250 limit in not that soft for regular EVE. I'll change to 300. @rene so the size of the image is still the issue and eve cannot grow beyond 300Mb in any near futur. I'm afraid VIM is still on my to-remove list :)

Why not remove `perf`?

2024-10-14 12:17 UTC, OhmSpectator approved these changes

2024-10-15 16:22 UTC, OhmSpectator commented
Looks fine to me, but we need @eriknordmark to approve (he has requested changes).

2024-10-15 18:14 UTC, eriknordmark approved these changes
LGTM but please create an issue to indicate that we need to get back to 250 again (even if that takes a while and might require to explore different approaches such as separating out some service containers like debug and edge-view, or figuring out which packages can be removed from various containers, or ...)

2024-10-15 18:52 UTC, OhmSpectator commented
> LGTM but please create an issue to indicate that we need to get back to 250 again (even if that takes a while and might require to explore different approaches such as separating out some service containers like debug and edge-view, or figuring out which packages can be removed from various containers, or ...)

https://github.com/lf-edge/eve/issues/4358

2024-10-15 23:33 UTC, merged