Kubevirt: Defer eve reboot/shutdown/update until drain completes
lf-edge/eve pull request #4494
Opened 2024-12-23 23:08 UTC by andrewd-zededa

As a part of kubevirt-eve we have multiple cluster nodes each
    hosting app workloads and volume replicas.  This implements defer
    for eve mgmt operations which will result in unavailability of storage
    replicas.  An example:
    
    1. Node 1 outage and recovers.
    2. Before volumes complete rebuilding on node 1: Node 2 outage and recovery.
    3. Volumes begin rebuilding replicas on nodes 1 and 2.
    4. User initiated request to reboot/shutdown/update eve-os on node3.
    5. That config request is set to defer until replicas are rebuilt on the other nodes.

2024-12-23 23:12 UTC, andrewd-zededa commented
```
  ./out has been created
  Modes: GitHubActions Robot InContainer ResetRepo UnitTests
  Processing: GH:4494
  GITHUB PR #4494 is being downloaded from
  https://api.github.com/repos/lf-edge/eve/pulls/4494
    JSON data at Mon Dec 23 11:09:31 PM UTC 2024
    Patch data at Mon Dec 23 11:09:32 PM UTC 2024
  ERROR: Unsure how to process GH:4494. Permissions missing?
```
An odd yetus failure, not sure what to make of this.

2025-01-20 16:15 UTC, andrewd-zededa commented
yetus checking seems broken:

2025-01-18T02:42:21.7383936Z ./out has been created
2025-01-18T02:42:22.0153173Z Modes: GitHubActions Robot InContainer ResetRepo UnitTests
2025-01-18T02:42:22.0153688Z Processing: GH:4494
2025-01-18T02:42:22.0158046Z GITHUB PR #4494 is being downloaded from
2025-01-18T02:42:22.0158544Z https://api.github.com/repos/lf-edge/eve/pulls/4494
2025-01-18T02:42:22.0172328Z   JSON data at Sat Jan 18 02:42:22 AM UTC 2025
2025-01-18T02:42:22.5937865Z   Patch data at Sat Jan 18 02:42:22 AM UTC 2025
2025-01-18T02:42:23.0465375Z ERROR: Unsure how to process GH:4494. Permissions missing?

2025-01-20 22:08 UTC, eriknordmark commented on pkg/pillar/cmd/baseosmgr/baseosmgr.go
> +	initNodeDrainPubSub(ps, &ctx)
The style in this file is to call some init functions around line 104 so it makes sense to follow that pattern for this additional description.

2025-01-20 22:09 UTC, eriknordmark commented on pkg/pillar/cmd/baseosmgr/handlebaseos.go
> +	// We want to wait to drain until we're sure we actually have a usable image local.
s/local/locally/ ?

2025-01-20 22:14 UTC, eriknordmark commented on pkg/pillar/cmd/baseosmgr/handlenodedrain.go
> +		return
Misplaced return?

2025-01-20 22:18 UTC, eriknordmark commented on pkg/pillar/cmd/baseosmgr/handlenodedrain.go
> +		ctx.deferredBaseOsID = id
Since drain can take a while there is a possibility that the user changes their mind about which new EVE version to use. Does the logic handle that by updating the deferredBaseOsID the user/API provides a new one while the update is deferred?

2025-01-20 22:24 UTC, eriknordmark commented on pkg/pillar/cmd/diag/handlenodedrain.go
> +	ctx.ph.Flush()
This doesn't follow the pattern for printing in diag.
Where there is an update to something which is printed, then the handlers should call triggerPrintOutput and the printOutput is where the actual information is printed.

Also, if the Status indicates some failure, wouldn't you want to print that as an with ERR prefix?

2025-01-20 22:26 UTC, eriknordmark commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +func handleNodeDrainStatusCreateNA(ctxArg interface{}, key string,
Why the "NA" suffix in the function names? We reuse the names across all of the agents so it is odd to have one agent add the agentname to some (but not all) of these functions.

2025-01-20 22:27 UTC, eriknordmark commented on pkg/pillar/cmd/baseosmgr/handlenodedrain.go
> +		log.Errorf("handleNodeDrainStatusImpl invalid type in configArg: %v", configArg)
In other agents you log.Fatal for this condition.

2025-01-20 22:28 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/handlenodedrain.go
> +		log.Errorf("handleNodeDrainStatusImpl invalid type in configArg: %v", configArg)
Ditto

2025-01-20 22:33 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/handleconfig.go
> +	drainInProgress           bool
The code reads as if this field has the semantics of waitForDrainComplete (or deferForDrain). Is that the semantics in zedagent?

2025-01-20 22:37 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/zedagent.go
> +		ctx.poweroffCmdDeferred = false
I don't see the code which sets poweroffCmdDeferred due to a drain.
Did you miss a function which sets the various deferred fields due to the local profile server API being used? (I don't recall whether that is a separate function from the controller API.)

2025-01-20 22:38 UTC, eriknordmark commented on pkg/pillar/cmd/zedkube/zedkube.go
> +	zedkubeCtx.subNodeDrainRequestZA, err = ps.NewSubscription(pubsub.SubscriptionOptions{
ZA? Why?

2025-01-20 22:42 UTC, eriknordmark commented on pkg/pillar/cmd/zedkube/zedkube.go
> +	}
This code would be readable if you put the current and new in some local variables instead of these very long lines of repeated calls to GobalValueInt.

2025-01-20 22:47 UTC, eriknordmark commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +	// NodeDrainStatus Failures here should keep drainInProgress set.
If there is something catastrophic happening to a cluster (e.g., two out of three nodes die due to hardware failures), is there a way to recover from that and make the single remaining node be usable e.g., as a one node cluster or as a standalone device?

It seems like a reboot might not be usable to recover since (based on this comment) you can't reboot until the drain has succeeded, and that is presumably impossible if the two other nodes died while you were trying to drain.
What happens when the drain timer fires?

Is there a  recovery case which does not involve a truck roll and a reinstall of EVE in such a case?

2025-01-20 22:51 UTC, eriknordmark requested changes
In addition to the detailed comments, I think the text in the PR description should go in a markdown file.

Also, at a high-level what are the pre-conditions for the reboot/shutdown/update?
Is it that all three nodes being healthy?
(That would ensure that if there is a hardware failure or crash of another node while this one is rebooting/updating that there is still one node left.)

If while the drain is in progress one of the other nodes in the cluster dies, should the reboot/update be deferred until that node is back?

2025-01-20 22:53 UTC, eriknordmark commented on pkg/pillar/cmd/zedkube/zedkube.go
> +			zedkubeCtx.drainOverrideTimer.Reset(5 * time.Minute)
Shouldn't you Stop the timer here as well like in the initial case?

2025-01-20 22:57 UTC, eriknordmark commented on pkg/pillar/cmd/diag/handlenodedrain.go
> +	ctx.ph.Print("INFO: Node Drain -> %s at %v\n", newStatus.Status.String(), ts)
Should this also go in the new console TUI? Check with @rucoder

2025-01-21 15:27 UTC, andrewd-zededa commented
Hi @eriknordmark thanks for the review, i'll address the docs changes and cleanup.

2025-01-21 16:33 UTC, andrewd-zededa commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +func handleNodeDrainStatusCreateNA(ctxArg interface{}, key string,
I think this was just a leftover of a refactoring, I'll clean it up

2025-01-21 17:05 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/handleconfig.go
> +	drainInProgress           bool
This follows the above updateInprogress usage to allow drain handling in handleNodeAgentStatusImpl()

2025-01-21 17:34 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedkube/zedkube.go
> +	}
absolutely, yes changing this

2025-01-21 18:10 UTC, andrewd-zededa commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +	// NodeDrainStatus Failures here should keep drainInProgress set.
If only a single cluster node is usable then etcd will be unable to form a quorum and k3s won't be able to meet the ready state. 

If the cluster is at the state of the local kubernetes node not running then applications should already be unavailable and the zedkube drain handler should just skip requesting drain.  There is already a handler to skip drain for one kubernetes outage type and return complete but I do see how this needs to be expanded to handle more kubernetes outage cases and more clearly show that zedkube is allowing these controller operations to be handled as recovery mechanisms and not just maintenance.  

The key here is to make sure to appropriately debounce these intermittent kubernetes api issues we could see due to timeouts.  This pr has a constant value of 180 seconds but I'm going to move this to a config-property to allow some modification.

2025-01-21 18:20 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/handleconfig.go
> +	drainInProgress           bool
I found the name potentially confusing since this is really about waiting and not starting/triggering a drain.

2025-01-21 18:27 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/zedagent.go
> +		ctx.poweroffCmdDeferred = false
FWIW that code is in pkg/pillar/cmd/zedagent/localinfo.go and presumably it needs the drainInProgress checks for poweroff, shutdown, and reboot.

2025-01-21 18:54 UTC, eriknordmark commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +	// NodeDrainStatus Failures here should keep drainInProgress set.
I was thinking of a different sequence.
1. Cluster is running with three nodes.
2. Controller (or LOC) requests a device reboot or EVE update of node X
3. Drain starts
4. Node Y fails/disappears from the cluster for any reason (hardware, software crash, network partition)

In such a case should we proceed with the device rebooot/update of node X? Or pause until Y is back in the cluster?

2025-01-21 23:55 UTC, andrewd-zededa commented on pkg/pillar/cmd/baseosmgr/baseosmgr.go
> +	initNodeDrainPubSub(ps, &ctx)
Fixed in latest push

2025-01-21 23:56 UTC, andrewd-zededa commented on pkg/pillar/cmd/baseosmgr/handlebaseos.go
> +	// We want to wait to drain until we're sure we actually have a usable image local.
Fixed in latest push

2025-01-21 23:56 UTC, andrewd-zededa commented on pkg/pillar/cmd/baseosmgr/handlenodedrain.go
> +		return
Removed return as fatal stops pillar

2025-01-21 23:58 UTC, andrewd-zededa commented on pkg/pillar/cmd/baseosmgr/handlenodedrain.go
> +		ctx.deferredBaseOsID = id
Moved the ctx.deferredBaseOsID out of the if statement so its updated on later calls which may have a different baseos id.

2025-01-21 23:59 UTC, andrewd-zededa commented on pkg/pillar/cmd/diag/handlenodedrain.go
> +	ctx.ph.Flush()
Fixed this so that printNodeDrainStatus() is called at the bottom of printOutput().

2025-01-21 23:59 UTC, andrewd-zededa commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +func handleNodeDrainStatusCreateNA(ctxArg interface{}, key string,
These must have been leftover from a previous refactor, cleaned them up.

2025-01-22 00:00 UTC, andrewd-zededa commented on pkg/pillar/cmd/baseosmgr/handlenodedrain.go
> +		log.Errorf("handleNodeDrainStatusImpl invalid type in configArg: %v", configArg)
I think in a previous review on this path the use of Fatal was disliked so I've converged on using Error for all type mismatch checks like this.  Still using Fatal on the subscription initialization failures though as seems to be the convention.

2025-01-22 00:03 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/handleconfig.go
> +	drainInProgress           bool
This follows the updateInprogress path of passing the drain state over to zedagent.go handleNodeAgentStatusImpl() to check before calling handleDeviceOperationCmd

2025-01-22 00:04 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/handleconfig.go
> +	drainInProgress           bool
I'm following now, I can reword it

2025-01-22 20:05 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/handleconfig.go
> +	drainInProgress           bool
Thanks

2025-01-24 18:24 UTC, andrewd-zededa commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +	// NodeDrainStatus Failures here should keep drainInProgress set.
If the cluster were to continue with the device operation in this situation, the remaining node would lose its ability to continue running as it will lose heartbeats from both other nodes.

2025-01-24 18:34 UTC, andrewd-zededa commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +	// NodeDrainStatus Failures here should keep drainInProgress set.
The cluster does recover when node X or Y return though.  The drain handler could be enhanced to watch node states and defer itself

2025-01-24 22:08 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/zedagent.go
> +		ctx.poweroffCmdDeferred = false
Thanks for the pointer, I think this is now resolved in the latest push.

2025-01-24 22:09 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/handleconfig.go
> +	drainInProgress           bool
Done in latest push.

2025-01-27 14:19 UTC, OhmSpectator commented
> ```
>   ./out has been created
>   Modes: GitHubActions Robot InContainer ResetRepo UnitTests
>   Processing: GH:4494
>   GITHUB PR #4494 is being downloaded from
>   https://api.github.com/repos/lf-edge/eve/pulls/4494
>     JSON data at Mon Dec 23 11:09:31 PM UTC 2024
>     Patch data at Mon Dec 23 11:09:32 PM UTC 2024
>   ERROR: Unsure how to process GH:4494. Permissions missing?
> ```
> 
> 
>     
>   
> 
> An odd yetus failure, not sure what to make of this.

@yash-zededa, could you please take a look? I remember you had an explanation for a similar situation.

2025-01-27 15:13 UTC, yash-zededa commented
@OhmSpectator  @andrewd-zededa For all the PRs (though quite few, I must say), I have noticed this issue occurs when there is a large number of files changed.


The error is from the script [here](https://github.com/apache/yetus/blob/a2a0af531bf90c97bc113948f7745c0fa6f7fad2/precommit/src/main/shell/core.d/patchfiles.sh#L177) 

Seems like it's a bug

2025-01-27 16:32 UTC, eriknordmark commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +	// NodeDrainStatus Failures here should keep drainInProgress set.
The cluster might be unusable (not able to run workloads) but even if it is one should be able to manage the device which is still reachable. Never ever again being able to reboot that device from the controller seems problematic to me. A recovery workflow (which scraps the cluster but recovers the one working device) might be to reconfigure the cluster to have only 1 member (or make the remaining node no longer be part of a cluster). But it is far from clear that this would work if a drain has started and not yet completed. Don't need to ensure that such a recovery path exists in this PR, but it is work that needs to be done.

2025-01-28 17:51 UTC, andrewd-zededa commented on pkg/pillar/cmd/nodeagent/handlenodedrain.go
> +	// NodeDrainStatus Failures here should keep drainInProgress set.
Ok, yeah I'm thinking a one option can be an eve config-property to allow drain bypass.

2025-01-28 17:53 UTC, andrewd-zededa commented on pkg/pillar/cmd/diag/handlenodedrain.go
> +	ctx.ph.Print("INFO: Node Drain -> %s at %v\n", newStatus.Status.String(), ts)
@eriknordmark this PR is already large enough to break yetus checking.  Can I submit the TUI eve-monitor change in a future PR?

2025-01-28 21:20 UTC, eriknordmark commented on pkg/pillar/cmd/diag/handlenodedrain.go
> +	ctx.ph.Print("INFO: Node Drain -> %s at %v\n", newStatus.Status.String(), ts)
OK

2025-01-28 21:20 UTC, eriknordmark approved these changes
LGTM

2025-01-29 13:35 UTC, merged