kubevirt: upgrade k3s,multus,kubevirt,cdi,longhorn
lf-edge/eve pull request #4501
Opened 2024-12-31 00:27 UTC by andrewd-zededa

A kube container generation number is tracked in cluster-update.sh
and compared to an 'applied' version in the persistent node fs /var/lib.
When the applied version is behind it triggers component upgrades.
cluster-update.sh uses an inline command in the zedkube micro service to publish
status updates to zedagent which will trigger info messages (ZInfoKubeClusterUpdateStatus) to a controller.

Signed-off-by: Andrew Durbin <andrewd@zededa.com>

2025-01-28 21:27 UTC, andrewd-zededa commented
added zedagent/nokube.go with go build pragmatic to not build with kubevirt, and added go build pragma to build zedagent/handleedgenodecluster.go only in kubevirt to handle HV=kvm build issues.

2025-01-28 21:55 UTC, andrewd-zededa commented
The same yetus failure due to too large go-mod vendor commit:

>   ./out has been created
>   Modes: GitHubActions Robot InContainer ResetRepo UnitTests
>   Processing: GH:4501
>   GITHUB PR #4501 is being downloaded from
>   https://api.github.com/repos/lf-edge/eve/pulls/4501
>     JSON data at Tue Jan 28 09:54:00 PM UTC 2025
>     Patch data at Tue Jan 28 09:54:01 PM UTC 2025
>   ERROR: Unsure how to process GH:4501. Permissions missing?

2025-01-29 17:23 UTC, andrewd-zededa commented
I just saw the conflict, I'll rebase

2025-01-31 00:28 UTC, andrewd-zededa commented
Rebase again, also fixed a series of yetus issues in infotypes.go and a few elsewhere.

2025-01-31 04:07 UTC, eriknordmark commented on pkg/kube/cluster-update.sh
> +Update_RunDescheduler() {
Where do you call this? And do you retry if there it returns on line 156 or line 160?

2025-01-31 04:08 UTC, eriknordmark approved these changes
Run tests

2025-01-31 15:52 UTC, andrewd-zededa commented on pkg/kube/cluster-update.sh
> +Update_RunDescheduler() {
In the other pr it is checked in the main pkg/kube/cluster-init.sh run loop near the bottom of the file

2025-01-31 16:03 UTC, andrewd-zededa commented
Removed misplaced `Update_RunDescheduler()` in latest push, should only be in #4506

2025-01-31 18:22 UTC, eriknordmark approved these changes
LGTM

2025-01-31 23:50 UTC, eriknordmark commented on pkg/pillar/cmd/zedkube/zedkube.go
> +	// if any args defined, will run that single command and exit.
Looks like you should use inlineIfargs in zedkube.go. That reduces memory footprint since the long-running not inline case will run as a goroutines in the zedbox process like our other long-running agents.

2025-01-31 23:56 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/zedagent.go
> +	kubeClusterUpdateTicker := time.NewTicker(1 * time.Minute)
Why isn't this triggered by a change i.e., as a result of the handleCreate/Modify/Delete being called by the collection you subscribe to?

2025-02-01 05:29 UTC, andrewd-zededa commented
Pushed a change to address the watchdog crash.   The crash was introduced with my refactoring to add zedagent/nokube.go.

2025-02-01 06:32 UTC, eriknordmark approved these changes
Re-try tests

2025-02-03 18:52 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/zedagent.go
> +	kubeClusterUpdateTicker := time.NewTicker(1 * time.Minute)
Under `handleClusterUpdateStatusImpl()` the subscription will run the same trigger path.  This ticker will help with connection outages.

2025-02-03 18:57 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedkube/zedkube.go
> +	// if any args defined, will run that single command and exit.
Good catch, fixed in latest push zedbox.go

2025-02-03 21:31 UTC, eriknordmark commented on pkg/pillar/cmd/zedkube/zedkube.go
> +	time.Sleep(time.Second * 1)
Since this is not part of the long-running agent you shouldn't do the StillRunning.
Why do you need to sleep before returning?

2025-02-03 21:41 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/zedagent.go
> +		case change, ok := <-checkClusterUpdateStatusChan(zedagentCtx):
I was surprised by this difference from the normal pattern.
How about documenting that we check ok here to handle the non-kubvirt case when we do not have that subscription.

And please add a log statement and check that this does not triggger all the time (busy loop) in the non-kubevirt case. (A closed channel might always trigger the select - I'm not sure)

2025-02-03 21:42 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/reportinfo.go
> +	if isUpdating(ctx) || isKubeClusterUpdating(ctx) {
I wonder if there is a place we can document this (that DEVICE_STATE_BASEOS_UPDATING is returned when any node in the cluster is updating - I assume that what it does ...)

2025-02-03 21:44 UTC, eriknordmark commented on pkg/kube/update-component/expected_versions.yaml
> +kubevirt: "v1.1.0-dirty"
dirty? Is this something temporary?

2025-02-03 22:03 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/reportinfo.go
> +	if isUpdating(ctx) || isKubeClusterUpdating(ctx) {
No this will only extend the local node's DEVICE_STATE_BASEOS_UPDATING if the post-baseos-update-reboot is taking longer to update kubernetes components.  Those components will be started with the first node to update, and the others should then just update their eve-os.

2025-02-03 22:30 UTC, eriknordmark commented on pkg/kube/update-component/README
> +./upgrades -c -d -n kube3 -l kubevirt,cdi,longhorn -f upgrades.yaml -u
Do you intend this document to be readable by a developer? Then adding a few words of context would make sense. If not, why is it called README?

For instance, is this an example or the exact command used to cause an update?

2025-02-03 23:02 UTC, andrewd-zededa commented on pkg/kube/update-component/README
> +./upgrades -c -d -n kube3 -l kubevirt,cdi,longhorn -f upgrades.yaml -u
Oh certainly, that's way too short

2025-02-03 23:09 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/reportinfo.go
> +	if isUpdating(ctx) || isKubeClusterUpdating(ctx) {
Ah

2025-02-04 00:06 UTC, eriknordmark requested changes
The select statement in zedagent reading from the closed channel does cause a busy wait on EVE kvm i.e., very high CPU load since it selects and then ok is false. So you need a different approach, e.g., not closing the channel.

2025-02-04 00:08 UTC, andrewd-zededa commented on pkg/kube/update-component/expected_versions.yaml
> +kubevirt: "v1.1.0-dirty"
Yes, still awaiting an official release.

2025-02-04 00:10 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/zedagent.go
> +	kubeClusterUpdateTicker := time.NewTicker(1 * time.Minute)
Ok, I can remove the ticker then

2025-02-04 04:08 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedkube/zedkube.go
> +	time.Sleep(time.Second * 1)
This will be removed, I think there was a suspicion of a message not persisting, but reviewing the pubsub socket driver I see it doesn't return from Publish until WriteRename completes.

2025-02-04 14:47 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/zedagent.go
> +	kubeClusterUpdateTicker := time.NewTicker(1 * time.Minute)
Removed in latest push

2025-02-04 14:47 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedkube/zedkube.go
> +	time.Sleep(time.Second * 1)
Removed in latest push

2025-02-04 14:50 UTC, andrewd-zededa commented on pkg/pillar/cmd/zedagent/zedagent.go
> +		case change, ok := <-checkClusterUpdateStatusChan(zedagentCtx):
Turns out it wasn't as large as expected to just pull into the main types so I moved the kubeapi file to pkg/pillar/types/clusterupdatetypes.go.  Sorry for the channel detour here.

2025-02-04 14:54 UTC, andrewd-zededa commented on pkg/kube/update-component/README
> +./upgrades -c -d -n kube3 -l kubevirt,cdi,longhorn -f upgrades.yaml -u
Latest push includes a longer pkg/kube/update-component/README.md instead.

2025-02-04 16:02 UTC, eriknordmark approved these changes
LGTM

2025-02-05 01:28 UTC, merged